// Code generated by cmd/codegen. DO NOT EDIT.

//go:build integration

package apitest

import (
	"fmt"
	"net/url"
	"strings"
	"testing"
)

func TestMaterialTypeCRUD(t *testing.T) {
	c := NewClient(t)
	c.Login(t)

	RunGeneratedKeyCRUD(t, c, GeneratedKeyCRUDCase{
		Name:     "material type",
		BasePath: "/api/material-types",
		CreateBody: map[string]any{
			"code":      "TEST_mat_type",
			"is_active": true,
			"name":      "Test material type",
		},
		UpdateBody: map[string]any{
			"name": "Updated test material type",
		},
		KeyFromBody: func(t *testing.T, body map[string]any) string {
			t.Helper()

			parts := []string{
				url.PathEscape(fmt.Sprint(IntFromJSON(t, body, "id"))),
			}
			return strings.Join(parts, "/")
		},
		CheckUpdated: func(t *testing.T, detail map[string]any) {
			t.Helper()

			if fmt.Sprint(detail["name"]) != "Updated test material type" {
				t.Fatalf("expected updated name, got %v", detail["name"])
			}
		},
	})
}
