// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func constructionSiteRoutes(api *webapp.Group) {
	api.POST(
		"/construction-sites",
		webapp.WithName("constructionSite.create"),
		webapp.WithPermission("constructionSite.create"),
		webapp.WithService("ConstructionSite", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.ConstructionSite]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/construction-sites",
		webapp.WithName("constructionSite.list"),
		webapp.WithPermission("constructionSite.list"),
		webapp.WithService("ConstructionSite", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/construction-sites/{id}",
		webapp.WithName("constructionSite.detail"),
		webapp.WithPermission("constructionSite.detail"),
		webapp.WithService("ConstructionSite", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/construction-sites/{id}",
		webapp.WithName("constructionSite.update"),
		webapp.WithPermission("constructionSite.update"),
		webapp.WithService("ConstructionSite", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.ConstructionSiteKey, *models.ConstructionSite]("id")),
	)

	api.DELETE(
		"/construction-sites/{id}",
		webapp.WithName("constructionSite.delete"),
		webapp.WithPermission("constructionSite.delete"),
		webapp.WithService("ConstructionSite", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
