// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func contactRoutes(api *webapp.Group) {
	api.POST(
		"/contacts",
		webapp.WithName("contact.create"),
		webapp.WithPermission("contact.create"),
		webapp.WithService("Contact", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.Contact]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/contacts",
		webapp.WithName("contact.list"),
		webapp.WithPermission("contact.list"),
		webapp.WithService("Contact", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/contacts/{id}",
		webapp.WithName("contact.detail"),
		webapp.WithPermission("contact.detail"),
		webapp.WithService("Contact", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/contacts/{id}",
		webapp.WithName("contact.update"),
		webapp.WithPermission("contact.update"),
		webapp.WithService("Contact", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.ContactKey, *models.Contact]("id")),
	)

	api.DELETE(
		"/contacts/{id}",
		webapp.WithName("contact.delete"),
		webapp.WithPermission("contact.delete"),
		webapp.WithService("Contact", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
