// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func employeePostRoutes(api *webapp.Group) {
	api.POST(
		"/employee-post",
		webapp.WithName("employeePost.create"),
		webapp.WithPermission("employeePost.create"),
		webapp.WithService("EmployeePost", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.EmployeePost]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/employee-post",
		webapp.WithName("employeePost.list"),
		webapp.WithPermission("employeePost.list"),
		webapp.WithService("EmployeePost", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/employee-post/{id}",
		webapp.WithName("employeePost.detail"),
		webapp.WithPermission("employeePost.detail"),
		webapp.WithService("EmployeePost", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/employee-post/{id}",
		webapp.WithName("employeePost.update"),
		webapp.WithPermission("employeePost.update"),
		webapp.WithService("EmployeePost", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.EmployeePostKey, *models.EmployeePost]("id")),
	)

	api.DELETE(
		"/employee-post/{id}",
		webapp.WithName("employeePost.delete"),
		webapp.WithPermission("employeePost.delete"),
		webapp.WithService("EmployeePost", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
