// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func entityContactRoutes(api *webapp.Group) {
	api.POST(
		"/entity-contacts",
		webapp.WithName("entityContact.create"),
		webapp.WithPermission("entityContact.create"),
		webapp.WithService("EntityContact", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.EntityContact]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/entity-contacts",
		webapp.WithName("entityContact.list"),
		webapp.WithPermission("entityContact.list"),
		webapp.WithService("EntityContact", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/entity-contacts/{id}",
		webapp.WithName("entityContact.detail"),
		webapp.WithPermission("entityContact.detail"),
		webapp.WithService("EntityContact", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/entity-contacts/{id}",
		webapp.WithName("entityContact.update"),
		webapp.WithPermission("entityContact.update"),
		webapp.WithService("EntityContact", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.EntityContactKey, *models.EntityContact]("id")),
	)

	api.DELETE(
		"/entity-contacts/{id}",
		webapp.WithName("entityContact.delete"),
		webapp.WithPermission("entityContact.delete"),
		webapp.WithService("EntityContact", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
