// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialRequestStatusRoutes(api *webapp.Group) {
	api.GET(
		"/material-request-statuses",
		webapp.WithName("materialRequestStatus.list"),
		webapp.WithPermission("materialRequestStatus.list"),
		webapp.WithService("MaterialRequestStatus", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-request-statuses/{id}",
		webapp.WithName("materialRequestStatus.detail"),
		webapp.WithPermission("materialRequestStatus.detail"),
		webapp.WithService("MaterialRequestStatus", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-request-statuses/{id}",
		webapp.WithName("materialRequestStatus.update"),
		webapp.WithPermission("materialRequestStatus.update"),
		webapp.WithService("MaterialRequestStatus", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialRequestStatusKey, *models.MaterialRequestStatus]("id")),
	)
}
