// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialRequestItemRoutes(api *webapp.Group) {
	api.POST(
		"/material-request-items",
		webapp.WithName("materialRequestItem.create"),
		webapp.WithPermission("materialRequestItem.create"),
		webapp.WithService("MaterialRequestItem", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialRequestItem]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-request-items",
		webapp.WithName("materialRequestItem.list"),
		webapp.WithPermission("materialRequestItem.list"),
		webapp.WithService("MaterialRequestItem", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-request-items/{id}",
		webapp.WithName("materialRequestItem.detail"),
		webapp.WithPermission("materialRequestItem.detail"),
		webapp.WithService("MaterialRequestItem", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-request-items/{id}",
		webapp.WithName("materialRequestItem.update"),
		webapp.WithPermission("materialRequestItem.update"),
		webapp.WithService("MaterialRequestItem", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialRequestItemKey, *models.MaterialRequestItem]("id")),
	)

	api.DELETE(
		"/material-request-items/{id}",
		webapp.WithName("materialRequestItem.delete"),
		webapp.WithPermission("materialRequestItem.delete"),
		webapp.WithService("MaterialRequestItem", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
