// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialTransferItemRoutes(api *webapp.Group) {
	api.POST(
		"/material-transfer-items",
		webapp.WithName("materialTransferItem.create"),
		webapp.WithPermission("materialTransferItem.create"),
		webapp.WithService("MaterialTransferItem", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialTransferItem]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-transfer-items",
		webapp.WithName("materialTransferItem.list"),
		webapp.WithPermission("materialTransferItem.list"),
		webapp.WithService("MaterialTransferItem", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-transfer-items/{id}",
		webapp.WithName("materialTransferItem.detail"),
		webapp.WithPermission("materialTransferItem.detail"),
		webapp.WithService("MaterialTransferItem", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-transfer-items/{id}",
		webapp.WithName("materialTransferItem.update"),
		webapp.WithPermission("materialTransferItem.update"),
		webapp.WithService("MaterialTransferItem", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialTransferItemKey, *models.MaterialTransferItem]("id")),
	)

	api.DELETE(
		"/material-transfer-items/{id}",
		webapp.WithName("materialTransferItem.delete"),
		webapp.WithPermission("materialTransferItem.delete"),
		webapp.WithService("MaterialTransferItem", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
