// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialConsumptionRoutes(api *webapp.Group) {
	api.POST(
		"/material-consumptions",
		webapp.WithName("materialConsumption.create"),
		webapp.WithPermission("materialConsumption.create"),
		webapp.WithService("MaterialConsumption", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialConsumption]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-consumptions",
		webapp.WithName("materialConsumption.list"),
		webapp.WithPermission("materialConsumption.list"),
		webapp.WithService("MaterialConsumption", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-consumptions/{id}",
		webapp.WithName("materialConsumption.detail"),
		webapp.WithPermission("materialConsumption.detail"),
		webapp.WithService("MaterialConsumption", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-consumptions/{id}",
		webapp.WithName("materialConsumption.update"),
		webapp.WithPermission("materialConsumption.update"),
		webapp.WithService("MaterialConsumption", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialConsumptionKey, *models.MaterialConsumption]("id")),
	)

	api.DELETE(
		"/material-consumptions/{id}",
		webapp.WithName("materialConsumption.delete"),
		webapp.WithPermission("materialConsumption.delete"),
		webapp.WithService("MaterialConsumption", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
