// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialReceiptItemRoutes(api *webapp.Group) {
	api.POST(
		"/material-receipt-items",
		webapp.WithName("materialReceiptItem.create"),
		webapp.WithPermission("materialReceiptItem.create"),
		webapp.WithService("MaterialReceiptItem", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialReceiptItem]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-receipt-items",
		webapp.WithName("materialReceiptItem.list"),
		webapp.WithPermission("materialReceiptItem.list"),
		webapp.WithService("MaterialReceiptItem", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-receipt-items/{id}",
		webapp.WithName("materialReceiptItem.detail"),
		webapp.WithPermission("materialReceiptItem.detail"),
		webapp.WithService("MaterialReceiptItem", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-receipt-items/{id}",
		webapp.WithName("materialReceiptItem.update"),
		webapp.WithPermission("materialReceiptItem.update"),
		webapp.WithService("MaterialReceiptItem", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialReceiptItemKey, *models.MaterialReceiptItem]("id")),
	)

	api.DELETE(
		"/material-receipt-items/{id}",
		webapp.WithName("materialReceiptItem.delete"),
		webapp.WithPermission("materialReceiptItem.delete"),
		webapp.WithService("MaterialReceiptItem", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
