// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialRoutes(api *webapp.Group) {
	api.POST(
		"/material",
		webapp.WithName("material.create"),
		webapp.WithPermission("material.create"),
		webapp.WithService("Material", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.Material]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material",
		webapp.WithName("material.list"),
		webapp.WithPermission("material.list"),
		webapp.WithService("Material", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material/{id}",
		webapp.WithName("material.detail"),
		webapp.WithPermission("material.detail"),
		webapp.WithService("Material", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material/{id}",
		webapp.WithName("material.update"),
		webapp.WithPermission("material.update"),
		webapp.WithService("Material", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialKey, *models.Material]("id")),
	)

	api.DELETE(
		"/material/{id}",
		webapp.WithName("material.delete"),
		webapp.WithPermission("material.delete"),
		webapp.WithService("Material", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
