// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialReceiptRoutes(api *webapp.Group) {
	api.POST(
		"/material-receipts",
		webapp.WithName("materialReceipt.create"),
		webapp.WithPermission("materialReceipt.create"),
		webapp.WithService("MaterialReceipt", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialReceipt]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-receipts",
		webapp.WithName("materialReceipt.list"),
		webapp.WithPermission("materialReceipt.list"),
		webapp.WithService("MaterialReceipt", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-receipts/{id}",
		webapp.WithName("materialReceipt.detail"),
		webapp.WithPermission("materialReceipt.detail"),
		webapp.WithService("MaterialReceipt", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-receipts/{id}",
		webapp.WithName("materialReceipt.update"),
		webapp.WithPermission("materialReceipt.update"),
		webapp.WithService("MaterialReceipt", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialReceiptKey, *models.MaterialReceipt]("id")),
	)

	api.DELETE(
		"/material-receipts/{id}",
		webapp.WithName("materialReceipt.delete"),
		webapp.WithPermission("materialReceipt.delete"),
		webapp.WithService("MaterialReceipt", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
