// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"github.com/dronm/webapp"
)

func materialRequestSupplierAssignmentItemRoutes(api *webapp.Group) {

	api.GET(
		"/material-request-supplier-assignment-items",
		webapp.WithName("materialRequestSupplierAssignmentItem.list"),
		webapp.WithPermission("materialRequestSupplierAssignmentItem.list"),
		webapp.WithService("MaterialRequestSupplierAssignmentItem", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-request-supplier-assignment-items/{id}",
		webapp.WithName("materialRequestSupplierAssignmentItem.detail"),
		webapp.WithPermission("materialRequestSupplierAssignmentItem.detail"),
		webapp.WithService("MaterialRequestSupplierAssignmentItem", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
