// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialTypeRoutes(api *webapp.Group) {
	api.POST(
		"/material-types",
		webapp.WithName("materialType.create"),
		webapp.WithPermission("materialType.create"),
		webapp.WithService("MaterialType", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialType]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-types",
		webapp.WithName("materialType.list"),
		webapp.WithPermission("materialType.list"),
		webapp.WithService("MaterialType", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-types/{id}",
		webapp.WithName("materialType.detail"),
		webapp.WithPermission("materialType.detail"),
		webapp.WithService("MaterialType", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-types/{id}",
		webapp.WithName("materialType.update"),
		webapp.WithPermission("materialType.update"),
		webapp.WithService("MaterialType", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialTypeKey, *models.MaterialType]("id")),
	)

	api.DELETE(
		"/material-types/{id}",
		webapp.WithName("materialType.delete"),
		webapp.WithPermission("materialType.delete"),
		webapp.WithService("MaterialType", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
