// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialRequestSupplierAssignmentRoutes(api *webapp.Group) {
	api.POST(
		"/material-request-supplier-assignments",
		webapp.WithName("materialRequestSupplierAssignment.create"),
		webapp.WithPermission("materialRequestSupplierAssignment.create"),
		webapp.WithService("MaterialRequestSupplierAssignment", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialRequestSupplierAssignment]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-request-supplier-assignments",
		webapp.WithName("materialRequestSupplierAssignment.list"),
		webapp.WithPermission("materialRequestSupplierAssignment.list"),
		webapp.WithService("MaterialRequestSupplierAssignment", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-request-supplier-assignments/{id}",
		webapp.WithName("materialRequestSupplierAssignment.detail"),
		webapp.WithPermission("materialRequestSupplierAssignment.detail"),
		webapp.WithService("MaterialRequestSupplierAssignment", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
