// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialRequestRoutes(api *webapp.Group) {
	api.POST(
		"/material-requests",
		webapp.WithName("materialRequest.create"),
		webapp.WithPermission("materialRequest.create"),
		webapp.WithService("MaterialRequest", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialRequest]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-requests",
		webapp.WithName("materialRequest.list"),
		webapp.WithPermission("materialRequest.list"),
		webapp.WithService("MaterialRequest", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-requests/{id}",
		webapp.WithName("materialRequest.detail"),
		webapp.WithPermission("materialRequest.detail"),
		webapp.WithService("MaterialRequest", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-requests/{id}",
		webapp.WithName("materialRequest.update"),
		webapp.WithPermission("materialRequest.update"),
		webapp.WithService("MaterialRequest", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialRequestKey, *models.MaterialRequest]("id")),
	)

	api.DELETE(
		"/material-requests/{id}",
		webapp.WithName("materialRequest.delete"),
		webapp.WithPermission("materialRequest.delete"),
		webapp.WithService("MaterialRequest", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
