// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialConsumptionItemRoutes(api *webapp.Group) {
	api.POST(
		"/material-consumption-items",
		webapp.WithName("materialConsumptionItem.create"),
		webapp.WithPermission("materialConsumptionItem.create"),
		webapp.WithService("MaterialConsumptionItem", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialConsumptionItem]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-consumption-items",
		webapp.WithName("materialConsumptionItem.list"),
		webapp.WithPermission("materialConsumptionItem.list"),
		webapp.WithService("MaterialConsumptionItem", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-consumption-items/{id}",
		webapp.WithName("materialConsumptionItem.detail"),
		webapp.WithPermission("materialConsumptionItem.detail"),
		webapp.WithService("MaterialConsumptionItem", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-consumption-items/{id}",
		webapp.WithName("materialConsumptionItem.update"),
		webapp.WithPermission("materialConsumptionItem.update"),
		webapp.WithService("MaterialConsumptionItem", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialConsumptionItemKey, *models.MaterialConsumptionItem]("id")),
	)

	api.DELETE(
		"/material-consumption-items/{id}",
		webapp.WithName("materialConsumptionItem.delete"),
		webapp.WithPermission("materialConsumptionItem.delete"),
		webapp.WithService("MaterialConsumptionItem", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
