// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialTransferRoutes(api *webapp.Group) {
	api.POST(
		"/material-transfers",
		webapp.WithName("materialTransfer.create"),
		webapp.WithPermission("materialTransfer.create"),
		webapp.WithService("MaterialTransfer", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialTransfer]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-transfers",
		webapp.WithName("materialTransfer.list"),
		webapp.WithPermission("materialTransfer.list"),
		webapp.WithService("MaterialTransfer", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-transfers/{id}",
		webapp.WithName("materialTransfer.detail"),
		webapp.WithPermission("materialTransfer.detail"),
		webapp.WithService("MaterialTransfer", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-transfers/{id}",
		webapp.WithName("materialTransfer.update"),
		webapp.WithPermission("materialTransfer.update"),
		webapp.WithService("MaterialTransfer", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialTransferKey, *models.MaterialTransfer]("id")),
	)

	api.DELETE(
		"/material-transfers/{id}",
		webapp.WithName("materialTransfer.delete"),
		webapp.WithPermission("materialTransfer.delete"),
		webapp.WithService("MaterialTransfer", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
