// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func materialStatusRoutes(api *webapp.Group) {
	api.POST(
		"/material-statuses",
		webapp.WithName("materialStatus.create"),
		webapp.WithPermission("materialStatus.create"),
		webapp.WithService("MaterialStatus", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MaterialStatus]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/material-statuses",
		webapp.WithName("materialStatus.list"),
		webapp.WithPermission("materialStatus.list"),
		webapp.WithService("MaterialStatus", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/material-statuses/{id}",
		webapp.WithName("materialStatus.detail"),
		webapp.WithPermission("materialStatus.detail"),
		webapp.WithService("MaterialStatus", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/material-statuses/{id}",
		webapp.WithName("materialStatus.update"),
		webapp.WithPermission("materialStatus.update"),
		webapp.WithService("MaterialStatus", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaterialStatusKey, *models.MaterialStatus]("id")),
	)

	api.DELETE(
		"/material-statuses/{id}",
		webapp.WithName("materialStatus.delete"),
		webapp.WithPermission("materialStatus.delete"),
		webapp.WithService("MaterialStatus", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
