// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func maxUserRoutes(api *webapp.Group) {

	api.GET(
		"/max-users",
		webapp.WithName("maxUser.list"),
		webapp.WithPermission("maxUser.list"),
		webapp.WithService("MaxUser", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/max-users/{id}",
		webapp.WithName("maxUser.detail"),
		webapp.WithPermission("maxUser.detail"),
		webapp.WithService("MaxUser", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/max-users/{id}",
		webapp.WithName("maxUser.update"),
		webapp.WithPermission("maxUser.update"),
		webapp.WithService("MaxUser", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MaxUserKey, *models.MaxUser]("id")),
	)

	api.DELETE(
		"/max-users/{id}",
		webapp.WithName("maxUser.delete"),
		webapp.WithPermission("maxUser.delete"),
		webapp.WithService("MaxUser", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
