// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func measureUnitRoutes(api *webapp.Group) {
	api.POST(
		"/measure-unit",
		webapp.WithName("measureUnit.create"),
		webapp.WithPermission("measureUnit.create"),
		webapp.WithService("MeasureUnit", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.MeasureUnit]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/measure-unit",
		webapp.WithName("measureUnit.list"),
		webapp.WithPermission("measureUnit.list"),
		webapp.WithService("MeasureUnit", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/measure-unit/{id}",
		webapp.WithName("measureUnit.detail"),
		webapp.WithPermission("measureUnit.detail"),
		webapp.WithService("MeasureUnit", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/measure-unit/{id}",
		webapp.WithName("measureUnit.update"),
		webapp.WithPermission("measureUnit.update"),
		webapp.WithService("MeasureUnit", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.MeasureUnitKey, *models.MeasureUnit]("id")),
	)

	api.DELETE(
		"/measure-unit/{id}",
		webapp.WithName("measureUnit.delete"),
		webapp.WithPermission("measureUnit.delete"),
		webapp.WithService("MeasureUnit", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
