// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func notificationTemplateRoutes(api *webapp.Group) {
	api.POST(
		"/notification-template",
		webapp.WithName("notificationTemplate.create"),
		webapp.WithPermission("notificationTemplate.create"),
		webapp.WithService("NotificationTemplate", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.NotificationTemplate]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/notification-template",
		webapp.WithName("notificationTemplate.list"),
		webapp.WithPermission("notificationTemplate.list"),
		webapp.WithService("NotificationTemplate", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/notification-template/{id}",
		webapp.WithName("notificationTemplate.detail"),
		webapp.WithPermission("notificationTemplate.detail"),
		webapp.WithService("NotificationTemplate", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/notification-template/{id}",
		webapp.WithName("notificationTemplate.update"),
		webapp.WithPermission("notificationTemplate.update"),
		webapp.WithService("NotificationTemplate", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.NotificationTemplateKey, *models.NotificationTemplate]("id")),
	)

	api.DELETE(
		"/notification-template/{id}",
		webapp.WithName("notificationTemplate.delete"),
		webapp.WithPermission("notificationTemplate.delete"),
		webapp.WithService("NotificationTemplate", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
