// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func orderImportanceRoutes(api *webapp.Group) {
	api.POST(
		"/order-importances",
		webapp.WithName("orderImportance.create"),
		webapp.WithPermission("orderImportance.create"),
		webapp.WithService("OrderImportance", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.OrderImportance]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/order-importances",
		webapp.WithName("orderImportance.list"),
		webapp.WithPermission("orderImportance.list"),
		webapp.WithService("OrderImportance", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/order-importances/{id}",
		webapp.WithName("orderImportance.detail"),
		webapp.WithPermission("orderImportance.detail"),
		webapp.WithService("OrderImportance", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/order-importances/{id}",
		webapp.WithName("orderImportance.update"),
		webapp.WithPermission("orderImportance.update"),
		webapp.WithService("OrderImportance", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.OrderImportanceKey, *models.OrderImportance]("id")),
	)

	api.DELETE(
		"/order-importances/{id}",
		webapp.WithName("orderImportance.delete"),
		webapp.WithPermission("orderImportance.delete"),
		webapp.WithService("OrderImportance", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
