// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import "github.com/dronm/webapp"

func registerGeneratedRoutes(api *webapp.Group) {
	constructionSiteRoutes(api)
	contactRoutes(api)
	employeePostRoutes(api)
	entityContactRoutes(api)
	materialRoutes(api)
	materialConsumptionRoutes(api)
	materialConsumptionItemRoutes(api)
	materialReceiptRoutes(api)
	materialReceiptItemRoutes(api)
	materialRequestRoutes(api)
	materialRequestItemRoutes(api)
	materialRequestStatusRoutes(api)
	materialStatusRoutes(api)
	materialTransferRoutes(api)
	materialTransferItemRoutes(api)
	materialTypeRoutes(api)
	maxUserRoutes(api)
	measureUnitRoutes(api)
	notificationTemplateRoutes(api)
	orderImportanceRoutes(api)
	supplierRoutes(api)
}
