// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
)

func supplierRoutes(api *webapp.Group) {
	api.POST(
		"/supplier",
		webapp.WithName("supplier.create"),
		webapp.WithPermission("supplier.create"),
		webapp.WithService("Supplier", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.Supplier]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/supplier",
		webapp.WithName("supplier.list"),
		webapp.WithPermission("supplier.list"),
		webapp.WithService("Supplier", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/supplier/{id}",
		webapp.WithName("supplier.detail"),
		webapp.WithPermission("supplier.detail"),
		webapp.WithService("Supplier", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/supplier/{id}",
		webapp.WithName("supplier.update"),
		webapp.WithPermission("supplier.update"),
		webapp.WithService("Supplier", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.SupplierKey, *models.Supplier]("id")),
	)

	api.DELETE(
		"/supplier/{id}",
		webapp.WithName("supplier.delete"),
		webapp.WithPermission("supplier.delete"),
		webapp.WithService("Supplier", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
