// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const constructionSiteRelation = "public.construction_sites"

// ConstructionSite describes an editable construction site reference entry.
type ConstructionSite struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the construction site.
	Name     string `json:"name" required:"true" maxLen:"250"`
	IsActive bool   `json:"is_active" required:"true"`
}

func (m ConstructionSite) Relation() string {
	return constructionSiteRelation
}

func (m ConstructionSite) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// ConstructionSiteKey is used for detail, update, and delete WHERE clauses.
type ConstructionSiteKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m ConstructionSiteKey) Relation() string {
	return constructionSiteRelation
}

type UpdateConstructionSiteRequest struct {
	ID    int
	Input modelbind.ModelInput[*ConstructionSite]
}
