// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const contactRelation = "public.contacts"

// Contact describes an editable contact reference entry.
type Contact struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the contact.
	Name string `json:"name" required:"true" maxLen:"250"`
	// Contact phone
	Phone string `json:"phone" maxLen:"11"`
	// Contact email
	Email *string `json:"email" maxLen:"150"`
	// contact post
	EmployeePostID *int `json:"employee_post_id"`
	IsActive       bool `json:"is_active" required:"true"`
	// Trigger calculated contact description
	Search *string `json:"search" srvCalc:"true"`
}

func (m Contact) Relation() string {
	return contactRelation
}

func (m Contact) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// ContactKey is used for detail, update, and delete WHERE clauses.
type ContactKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m ContactKey) Relation() string {
	return contactRelation
}

type UpdateContactRequest struct {
	ID    int
	Input modelbind.ModelInput[*Contact]
}
