// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const employeePostRelation = "public.employee_posts"

// EmployeePost describes an editable post unit reference entry.
type EmployeePost struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the post.
	Name     string `json:"name" required:"true"`
	IsActive bool   `json:"is_active" required:"true"`
}

func (m EmployeePost) Relation() string {
	return employeePostRelation
}

func (m EmployeePost) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// EmployeePostKey is used for detail, update, and delete WHERE clauses.
type EmployeePostKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m EmployeePostKey) Relation() string {
	return employeePostRelation
}

type UpdateEmployeePostRequest struct {
	ID    int
	Input modelbind.ModelInput[*EmployeePost]
}
