// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const entityContactRelation = "public.entity_contacts"

// EntityContact links a contact to an application entity.
type EntityContact struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Application entity type.
	EntityType string `json:"entity_type" required:"true" maxLen:"250"`
	// Application entity identifier.
	EntityID int `json:"entity_id" required:"true"`
	// Contact reference.
	ContactID int  `json:"contact_id" required:"true"`
	IsActive  bool `json:"is_active" required:"true"`
}

func (m EntityContact) Relation() string {
	return entityContactRelation
}

func (m EntityContact) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const entityContactListRelation = "public.entity_contacts_list"

// EntityContactList is the collection projection for entity contacts.
type EntityContactList struct {
	ID           int       `json:"id" primaryKey:"true"`
	EntityType   string    `json:"entity_type" required:"true"`
	EntityID     int       `json:"entity_id" required:"true"`
	Entity       *Ref      `json:"entity"`
	ContactID    int       `json:"contact_id" required:"true"`
	Contact      *Ref      `json:"contact" required:"true"`
	ContactAttrs JSONValue `json:"contact_attrs" required:"true"`
	IsActive     bool      `json:"is_active" required:"true"`
}

func (m EntityContactList) Relation() string {
	return entityContactListRelation
}

func (m EntityContactList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// EntityContactKey is used for detail, update, and delete WHERE clauses.
type EntityContactKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m EntityContactKey) Relation() string {
	return entityContactRelation
}

type UpdateEntityContactRequest struct {
	ID    int
	Input modelbind.ModelInput[*EntityContact]
}
