// Code generated by cmd/codegen. DO NOT EDIT.
// Backend enum artifact: managed by Codegen.

package models

import (
	"fmt"
	"slices"

	"github.com/dronm/modelbind/metadata"
)

func init() {
	RegisterGeneratedModelbindEnums()
}

// RegisterGeneratedModelbindEnums merges schema-owned enums into modelbind.
// Package initialization calls it automatically. If application startup replaces
// metadata.Enums, call this again afterward and before parsing model metadata.
// This is a startup-only function: do not call concurrently with request handling.
// It preserves unrelated enums and panics instead of replacing conflicting values.
func RegisterGeneratedModelbindEnums() {
	definitions := []struct {
		name   string
		values []string
	}{
		{
			name: "material_status_type",
			values: []string{
				"at_work",
				"on_maintenance",
			},
		},
	}
	// Check every entry before mutating the registry.
	for _, definition := range definitions {
		if existing, ok := metadata.Enums[definition.name]; ok && !slices.Equal(existing, definition.values) {
			panic(fmt.Sprintf("Codegen: modelbind enum %q is already registered with conflicting values: got %v, want %v; use one registration owner", definition.name, existing, definition.values))
		}
	}
	if metadata.Enums == nil {
		metadata.Enums = make(map[string][]string, len(definitions))
	}
	for _, definition := range definitions {
		metadata.Enums[definition.name] = definition.values
	}
}
