// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialTransferRelation = "public.material_transfers"

// MaterialTransfer describes a material transfer document between construction sites.
type MaterialTransfer struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Document date and time.
	Date time.Time `json:"date" required:"true"`
	// Construction site materials are transferred from.
	SourceConstructionSiteID int `json:"source_construction_site_id" required:"true"`
	// Construction site materials are transferred to.
	DestinationConstructionSiteID int `json:"destination_construction_site_id" required:"true"`
	// Optional document comment.
	Comment *string `json:"comment"`
	// Optimistic concurrency version.
	Version int `json:"version" required:"true" srvCalc:"true"`
}

func (m MaterialTransfer) Relation() string {
	return materialTransferRelation
}

func (m MaterialTransfer) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialTransferListRelation = "public.material_transfers_list"

// MaterialTransferList is the collection projection for material transfers.
type MaterialTransferList struct {
	ID                            int       `json:"id" primaryKey:"true"`
	Date                          time.Time `json:"date" required:"true"`
	SourceConstructionSiteID      int       `json:"source_construction_site_id" required:"true"`
	DestinationConstructionSiteID int       `json:"destination_construction_site_id" required:"true"`
	Comment                       *string   `json:"comment"`
	Version                       int       `json:"version" required:"true"`
	SourceConstructionSite        *Ref      `json:"source_construction_site"`
	DestinationConstructionSite   *Ref      `json:"destination_construction_site"`
}

func (m MaterialTransferList) Relation() string {
	return materialTransferListRelation
}

func (m MaterialTransferList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialTransferKey is used for detail, update, and delete WHERE clauses.
type MaterialTransferKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialTransferKey) Relation() string {
	return materialTransferRelation
}

type UpdateMaterialTransferRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialTransfer]
}
