// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	wmodels "github.com/dronm/webapp/models"
)

const materialRequestSupplierAssignmentItemRelation = "public.material_request_supplier_assignment_items"

// MaterialRequestSupplierAssignmentItem records the supplier selected for one material request line.
type MaterialRequestSupplierAssignmentItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the supplier assignment document.
	LineNum int `json:"line_num" required:"true"`
	// Parent supplier assignment document.
	MaterialRequestSupplierAssignmentID int `json:"material_request_supplier_assignment_id" required:"true"`
	// Material request line receiving a supplier assignment.
	MaterialRequestItemID int `json:"material_request_item_id" required:"true"`
	// Supplier selected for the material request line.
	SupplierID int `json:"supplier_id" required:"true"`
}

func (m MaterialRequestSupplierAssignmentItem) Relation() string {
	return materialRequestSupplierAssignmentItemRelation
}

func (m MaterialRequestSupplierAssignmentItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialRequestSupplierAssignmentItemListRelation = "public.material_request_supplier_assignment_items_list"

// MaterialRequestSupplierAssignmentItemList is the collection projection for material request supplier assignment items.
type MaterialRequestSupplierAssignmentItemList struct {
	ID                                  int  `json:"id" primaryKey:"true"`
	LineNum                             int  `json:"line_num" required:"true"`
	MaterialRequestSupplierAssignmentID int  `json:"material_request_supplier_assignment_id" required:"true"`
	MaterialRequestItemID               int  `json:"material_request_item_id" required:"true"`
	SupplierID                          int  `json:"supplier_id" required:"true"`
	Supplier                            *Ref `json:"supplier" required:"true"`
}

func (m MaterialRequestSupplierAssignmentItemList) Relation() string {
	return materialRequestSupplierAssignmentItemListRelation
}

func (m MaterialRequestSupplierAssignmentItemList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialRequestSupplierAssignmentItemKey is used for detail, update, and delete WHERE clauses.
type MaterialRequestSupplierAssignmentItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialRequestSupplierAssignmentItemKey) Relation() string {
	return materialRequestSupplierAssignmentItemRelation
}
