// Code generated by cmd/codegen. DO NOT EDIT.
// Backend enum artifact: managed by Codegen.

package models

// MaterialStatusType is the string enum registered as "material_status_type".
type MaterialStatusType string

const (
	MaterialStatusTypeAtWork        MaterialStatusType = "at_work"
	MaterialStatusTypeOnMaintenance MaterialStatusType = "on_maintenance"
)

// MaterialStatusTypeValues returns a fresh slice in schema order.
func MaterialStatusTypeValues() []string {
	return []string{
		string(MaterialStatusTypeAtWork),
		string(MaterialStatusTypeOnMaintenance),
	}
}

// IsValid reports whether v is one of the declared enum values.
func (v MaterialStatusType) IsValid() bool {
	switch v {
	case MaterialStatusTypeAtWork:
		return true
	case MaterialStatusTypeOnMaintenance:
		return true
	default:
		return false
	}
}

func (v MaterialStatusType) String() string {
	return string(v)
}
