// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	wmodels "github.com/dronm/webapp/models"
	"time"
)

const materialRequestSupplierAssignmentRelation = "public.material_request_supplier_assignments"

// MaterialRequestSupplierAssignment records a supply manager's supplier assignments for submitted material request lines.
type MaterialRequestSupplierAssignment struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Date and time when the supplier assignments were submitted.
	Date time.Time `json:"date" required:"true"`
	// Supply manager who submitted the supplier assignments.
	SupplyManagerID int `json:"supply_manager_id" required:"true" srvCalc:"true"`
	// Optional document comment.
	Comment *string `json:"comment"`
	// Optimistic concurrency version.
	Version int `json:"version" required:"true" srvCalc:"true"`
}

func (m MaterialRequestSupplierAssignment) Relation() string {
	return materialRequestSupplierAssignmentRelation
}

func (m MaterialRequestSupplierAssignment) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialRequestSupplierAssignmentListRelation = "public.material_request_supplier_assignments_list"

// MaterialRequestSupplierAssignmentList is the collection projection for material request supplier assignments.
type MaterialRequestSupplierAssignmentList struct {
	ID              int       `json:"id" primaryKey:"true"`
	Date            time.Time `json:"date" required:"true"`
	SupplyManagerID int       `json:"supply_manager_id" required:"true"`
	Comment         *string   `json:"comment"`
	Version         int       `json:"version" required:"true"`
	SupplyManager   *Ref      `json:"supply_manager" required:"true"`
}

func (m MaterialRequestSupplierAssignmentList) Relation() string {
	return materialRequestSupplierAssignmentListRelation
}

func (m MaterialRequestSupplierAssignmentList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialRequestSupplierAssignmentKey is used for detail, update, and delete WHERE clauses.
type MaterialRequestSupplierAssignmentKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialRequestSupplierAssignmentKey) Relation() string {
	return materialRequestSupplierAssignmentRelation
}
