// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialConsumptionRelation = "public.material_consumptions"

// MaterialConsumption describes a material consumption document.
type MaterialConsumption struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Document date and time.
	Date time.Time `json:"date" required:"true"`
	// Construction site consuming the materials.
	ConstructionSiteID int `json:"construction_site_id" required:"true"`
	// Optional document comment.
	Comment *string `json:"comment"`
	// Optimistic concurrency version.
	Version int `json:"version" required:"true" srvCalc:"true"`
}

func (m MaterialConsumption) Relation() string {
	return materialConsumptionRelation
}

func (m MaterialConsumption) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialConsumptionListRelation = "public.material_consumptions_list"

// MaterialConsumptionList is the collection projection for material consumptions.
type MaterialConsumptionList struct {
	ID                 int       `json:"id" primaryKey:"true"`
	Date               time.Time `json:"date" required:"true"`
	ConstructionSiteID int       `json:"construction_site_id" required:"true"`
	Comment            *string   `json:"comment"`
	Version            int       `json:"version" required:"true"`
	ConstructionSite   *Ref      `json:"construction_site"`
}

func (m MaterialConsumptionList) Relation() string {
	return materialConsumptionListRelation
}

func (m MaterialConsumptionList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialConsumptionKey is used for detail, update, and delete WHERE clauses.
type MaterialConsumptionKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialConsumptionKey) Relation() string {
	return materialConsumptionRelation
}

type UpdateMaterialConsumptionRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialConsumption]
}
