// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialConsumptionItemRelation = "public.material_consumption_items"

// MaterialConsumptionItem describes a line of a material consumption document.
type MaterialConsumptionItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the document.
	LineNum int `json:"line_num" required:"true"`
	// Parent material consumption document.
	MaterialConsumptionID int `json:"material_consumption_id" required:"true"`
	// Material.
	MaterialID int `json:"material_id" required:"true"`
	// Measurement unit.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Material quantity.
	Quant float64 `json:"quant" required:"true"`
}

func (m MaterialConsumptionItem) Relation() string {
	return materialConsumptionItemRelation
}

func (m MaterialConsumptionItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialConsumptionItemListRelation = "public.material_consumption_items_list"

// MaterialConsumptionItemList is the collection projection for material consumption items.
type MaterialConsumptionItemList struct {
	ID                    int     `json:"id" primaryKey:"true"`
	LineNum               int     `json:"line_num" required:"true"`
	MaterialConsumptionID int     `json:"material_consumption_id" required:"true"`
	MaterialID            int     `json:"material_id" required:"true"`
	MeasureUnitID         int     `json:"measure_unit_id" required:"true"`
	Quant                 float64 `json:"quant" required:"true"`
	Material              *Ref    `json:"material"`
	MeasureUnit           *Ref    `json:"measure_unit"`
}

func (m MaterialConsumptionItemList) Relation() string {
	return materialConsumptionItemListRelation
}

func (m MaterialConsumptionItemList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialConsumptionItemKey is used for detail, update, and delete WHERE clauses.
type MaterialConsumptionItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialConsumptionItemKey) Relation() string {
	return materialConsumptionItemRelation
}

type UpdateMaterialConsumptionItemRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialConsumptionItem]
}
