// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialRequestItemRelation = "public.material_request_items"

// MaterialRequestItem describes a line of a material request document.
type MaterialRequestItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the document.
	LineNum int `json:"line_num" required:"true"`
	// Parent material request document.
	MaterialRequestID int `json:"material_request_id" required:"true"`
	// Requested material.
	MaterialID int `json:"material_id" required:"true"`
	// Measurement unit copied from the selected material.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Requested quantity.
	Quant float64 `json:"quant" required:"true"`
	// Optional supplier assigned by a supply manager.
	SupplierID *int `json:"supplier_id"`
	// Optional date by which the material is required.
	RequiredDate *time.Time `json:"required_date"`
	// Request importance level.
	OrderImportanceID int `json:"order_importance_id" required:"true"`
	// Request item workflow status; new lines start in draft status.
	StatusID int `json:"status_id" required:"true"`
}

func (m MaterialRequestItem) Relation() string {
	return materialRequestItemRelation
}

func (m MaterialRequestItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialRequestItemListRelation = "public.material_request_items_list"

// MaterialRequestItemList is the collection projection for material request items.
type MaterialRequestItemList struct {
	ID                int        `json:"id" primaryKey:"true"`
	LineNum           int        `json:"line_num" required:"true"`
	MaterialRequestID int        `json:"material_request_id" required:"true"`
	MaterialID        int        `json:"material_id" required:"true"`
	MeasureUnitID     int        `json:"measure_unit_id" required:"true"`
	Quant             float64    `json:"quant" required:"true"`
	SupplierID        *int       `json:"supplier_id"`
	RequiredDate      *time.Time `json:"required_date"`
	OrderImportanceID int        `json:"order_importance_id" required:"true"`
	StatusID          int        `json:"status_id" required:"true"`
	Material          *Ref       `json:"material" required:"true"`
	MeasureUnit       *Ref       `json:"measure_unit" required:"true"`
	Supplier          *Ref       `json:"supplier"`
	OrderImportance   *Ref       `json:"order_importance" required:"true"`
	Status            *Ref       `json:"status" required:"true"`
}

func (m MaterialRequestItemList) Relation() string {
	return materialRequestItemListRelation
}

func (m MaterialRequestItemList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialRequestItemKey is used for detail, update, and delete WHERE clauses.
type MaterialRequestItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialRequestItemKey) Relation() string {
	return materialRequestItemRelation
}

type UpdateMaterialRequestItemRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialRequestItem]
}
