// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialReceiptRelation = "public.material_receipts"

// MaterialReceipt describes a material receipt document.
type MaterialReceipt struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Document date and time.
	Date time.Time `json:"date" required:"true"`
	// Optional default site for receipt lines without a site override.
	ConstructionSiteID *int `json:"construction_site_id"`
	// Material supplier.
	SupplierID int `json:"supplier_id" required:"true"`
	// Document number.
	Number string `json:"number" required:"true"`
	// Optional document comment.
	Comment *string `json:"comment"`
	// Optimistic concurrency version.
	Version int `json:"version" required:"true" srvCalc:"true"`
}

func (m MaterialReceipt) Relation() string {
	return materialReceiptRelation
}

func (m MaterialReceipt) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialReceiptListRelation = "public.material_receipts_list"

// MaterialReceiptList is the collection projection for material receipts.
type MaterialReceiptList struct {
	ID                 int       `json:"id" primaryKey:"true"`
	Date               time.Time `json:"date" required:"true"`
	ConstructionSiteID *int      `json:"construction_site_id"`
	SupplierID         int       `json:"supplier_id" required:"true"`
	Number             string    `json:"number" required:"true"`
	Comment            *string   `json:"comment"`
	Version            int       `json:"version" required:"true"`
	ConstructionSite   *Ref      `json:"construction_site"`
	Supplier           *Ref      `json:"supplier"`
}

func (m MaterialReceiptList) Relation() string {
	return materialReceiptListRelation
}

func (m MaterialReceiptList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialReceiptKey is used for detail, update, and delete WHERE clauses.
type MaterialReceiptKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialReceiptKey) Relation() string {
	return materialReceiptRelation
}

type UpdateMaterialReceiptRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialReceipt]
}
