// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialReceiptItemRelation = "public.material_receipt_items"

// MaterialReceiptItem describes a line of a material receipt document.
type MaterialReceiptItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the document.
	LineNum int `json:"line_num" required:"true"`
	// Parent material receipt document.
	MaterialReceiptID int `json:"material_receipt_id" required:"true"`
	// Material.
	MaterialID int `json:"material_id" required:"true"`
	// Measurement unit.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Optional line site; when null, use the receipt header site.
	ConstructionSiteID *int `json:"construction_site_id"`
	// Material quantity.
	Quant float64 `json:"quant" required:"true"`
	// Unit price.
	Price float64 `json:"price" required:"true"`
	// Line amount with VAT.
	Amount float64 `json:"amount" required:"true"`
	// Line vat percent.
	VatPercent float64 `json:"vat_percent" required:"true"`
	// Line vat amount.
	VatAmount float64 `json:"vat_amount" required:"true"`
}

func (m MaterialReceiptItem) Relation() string {
	return materialReceiptItemRelation
}

func (m MaterialReceiptItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialReceiptItemListRelation = "public.material_receipt_items_list"

// MaterialReceiptItemList is the collection projection for material receipt items.
type MaterialReceiptItemList struct {
	ID                 int     `json:"id" primaryKey:"true"`
	LineNum            int     `json:"line_num" required:"true"`
	MaterialReceiptID  int     `json:"material_receipt_id" required:"true"`
	MaterialID         int     `json:"material_id" required:"true"`
	MeasureUnitID      int     `json:"measure_unit_id" required:"true"`
	ConstructionSiteID *int    `json:"construction_site_id"`
	Quant              float64 `json:"quant" required:"true"`
	Price              float64 `json:"price" required:"true"`
	Amount             float64 `json:"amount" required:"true"`
	VatPercent         float64 `json:"vat_percent" required:"true"`
	VatAmount          float64 `json:"vat_amount" required:"true"`
	Material           *Ref    `json:"material"`
	MeasureUnit        *Ref    `json:"measure_unit"`
	ConstructionSite   *Ref    `json:"construction_site"`
}

func (m MaterialReceiptItemList) Relation() string {
	return materialReceiptItemListRelation
}

func (m MaterialReceiptItemList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialReceiptItemKey is used for detail, update, and delete WHERE clauses.
type MaterialReceiptItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialReceiptItemKey) Relation() string {
	return materialReceiptItemRelation
}

type UpdateMaterialReceiptItemRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialReceiptItem]
}
