// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialRequestRelation = "public.material_requests"

// MaterialRequest describes a request for materials at a construction site.
type MaterialRequest struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Document date and time.
	Date time.Time `json:"date" required:"true"`
	// Construction site requesting the materials.
	ConstructionSiteID int `json:"construction_site_id" required:"true"`
	// Manager responsible for the material request.
	ConstructionManagerID int `json:"construction_manager_id" required:"true"`
	// Optional document comment.
	Comment *string `json:"comment"`
	// Optimistic concurrency version.
	Version int `json:"version" required:"true" srvCalc:"true"`
	// Request workflow status maintained from the statuses of its lines.
	StatusID int `json:"status_id" required:"true" srvCalc:"true"`
}

func (m MaterialRequest) Relation() string {
	return materialRequestRelation
}

func (m MaterialRequest) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialRequestListRelation = "public.material_requests_list"

// MaterialRequestList is the collection projection for material requests.
type MaterialRequestList struct {
	ID                    int       `json:"id" primaryKey:"true"`
	Date                  time.Time `json:"date" required:"true"`
	ConstructionSiteID    int       `json:"construction_site_id" required:"true"`
	ConstructionManagerID int       `json:"construction_manager_id" required:"true"`
	Comment               *string   `json:"comment"`
	Version               int       `json:"version" required:"true"`
	ConstructionSite      *Ref      `json:"construction_site" required:"true"`
	ConstructionManager   *Ref      `json:"construction_manager" required:"true"`
	StatusID              int       `json:"status_id" required:"true"`
	Status                *Ref      `json:"status" required:"true"`
}

func (m MaterialRequestList) Relation() string {
	return materialRequestListRelation
}

func (m MaterialRequestList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialRequestKey is used for detail, update, and delete WHERE clauses.
type MaterialRequestKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialRequestKey) Relation() string {
	return materialRequestRelation
}

type UpdateMaterialRequestRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialRequest]
}
