// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialTransferItemRelation = "public.material_transfer_items"

// MaterialTransferItem describes a line of a material transfer document.
type MaterialTransferItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the document.
	LineNum int `json:"line_num" required:"true"`
	// Parent material transfer document.
	MaterialTransferID int `json:"material_transfer_id" required:"true"`
	// Material.
	MaterialID int `json:"material_id" required:"true"`
	// Measurement unit.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Material quantity.
	Quant float64 `json:"quant" required:"true"`
}

func (m MaterialTransferItem) Relation() string {
	return materialTransferItemRelation
}

func (m MaterialTransferItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialTransferItemListRelation = "public.material_transfer_items_list"

// MaterialTransferItemList is the collection projection for material transfer items.
type MaterialTransferItemList struct {
	ID                 int     `json:"id" primaryKey:"true"`
	LineNum            int     `json:"line_num" required:"true"`
	MaterialTransferID int     `json:"material_transfer_id" required:"true"`
	MaterialID         int     `json:"material_id" required:"true"`
	MeasureUnitID      int     `json:"measure_unit_id" required:"true"`
	Quant              float64 `json:"quant" required:"true"`
	Material           *Ref    `json:"material"`
	MeasureUnit        *Ref    `json:"measure_unit"`
}

func (m MaterialTransferItemList) Relation() string {
	return materialTransferItemListRelation
}

func (m MaterialTransferItemList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialTransferItemKey is used for detail, update, and delete WHERE clauses.
type MaterialTransferItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialTransferItemKey) Relation() string {
	return materialTransferItemRelation
}

type UpdateMaterialTransferItemRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialTransferItem]
}
