// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialTypeRelation = "public.material_types"

// MaterialType describes an editable material type unit reference entry.
type MaterialType struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Unique material type code
	Code string `json:"code" required:"true" maxLen:"80"`
	// Display name of the material type.
	Name     string `json:"name" required:"true"`
	IsActive bool   `json:"is_active" required:"true"`
}

func (m MaterialType) Relation() string {
	return materialTypeRelation
}

func (m MaterialType) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialTypeKey is used for detail, update, and delete WHERE clauses.
type MaterialTypeKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialTypeKey) Relation() string {
	return materialTypeRelation
}

type UpdateMaterialTypeRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialType]
}
