// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialRequestStatusRelation = "public.material_request_statuses"

// MaterialRequestStatus describes an editable material request item status reference entry.
type MaterialRequestStatus struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Stable status code used by the material request workflow.
	Code string `json:"code" required:"true" srvCalc:"true" maxLen:"40"`
	// Display name of the status.
	Name string `json:"name" required:"true"`
}

func (m MaterialRequestStatus) Relation() string {
	return materialRequestStatusRelation
}

func (m MaterialRequestStatus) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialRequestStatusKey is used for detail, update, and delete WHERE clauses.
type MaterialRequestStatusKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialRequestStatusKey) Relation() string {
	return materialRequestStatusRelation
}

type UpdateMaterialRequestStatusRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialRequestStatus]
}
