// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialRelation = "public.materials"

// Material describes an editable material reference entry.
type Material struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the material.
	Name string `json:"name" required:"true" maxLen:"500"`
	// Full name of the material.
	NameFull *string `json:"name_full"`
	// Base measurement unit of the material.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Material type unit of the material.
	MaterialTypeID int  `json:"material_type_id" required:"true"`
	IsActive       bool `json:"is_active" required:"true"`
}

func (m Material) Relation() string {
	return materialRelation
}

func (m Material) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialListRelation = "public.materials_list"

// MaterialList is the collection projection for materials.
type MaterialList struct {
	ID             int       `json:"id" primaryKey:"true"`
	Name           string    `json:"name" required:"true"`
	NameFull       *string   `json:"name_full"`
	MeasureUnitID  int       `json:"measure_unit_id" required:"true"`
	MeasureUnit    *Ref      `json:"measure_unit" required:"true"`
	MaterialTypeID int       `json:"material_type_id" required:"true"`
	MaterialType   *Ref      `json:"material_type" required:"true"`
	IsActive       bool      `json:"is_active" required:"true"`
	Balances       JSONValue `json:"balances" required:"true"`
}

func (m MaterialList) Relation() string {
	return materialListRelation
}

func (m MaterialList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialKey is used for detail, update, and delete WHERE clauses.
type MaterialKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialKey) Relation() string {
	return materialRelation
}

type UpdateMaterialRequest struct {
	ID    int
	Input modelbind.ModelInput[*Material]
}
