// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const materialStatusRelation = "public.material_statuses"

// MaterialStatus describes an editable material status unit reference entry.
type MaterialStatus struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Document date and time
	CreatedAt time.Time `json:"created_at" required:"true"`
	// Material reference
	MaterialID int `json:"material_id" required:"true"`
	// Construction site where the status change was recorded
	ConstructionSiteID *int `json:"construction_site_id"`
	// Material status
	Status   MaterialStatusType `json:"status" required:"true" enum:"material_status_type"`
	IsActive bool               `json:"is_active" required:"true"`
}

func (m MaterialStatus) Relation() string {
	return materialStatusRelation
}

func (m MaterialStatus) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const materialStatusListRelation = "public.material_statuses_list"

// MaterialStatusList is the collection projection for material statuses.
type MaterialStatusList struct {
	ID                 int                `json:"id" primaryKey:"true"`
	CreatedAt          time.Time          `json:"created_at" required:"true"`
	MaterialID         int                `json:"material_id" required:"true"`
	Material           *Ref               `json:"material" required:"true"`
	Status             MaterialStatusType `json:"status" required:"true" enum:"material_status_type"`
	IsActive           bool               `json:"is_active" required:"true"`
	ConstructionSiteID *int               `json:"construction_site_id"`
	ConstructionSite   *Ref               `json:"construction_site"`
}

func (m MaterialStatusList) Relation() string {
	return materialStatusListRelation
}

func (m MaterialStatusList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaterialStatusKey is used for detail, update, and delete WHERE clauses.
type MaterialStatusKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaterialStatusKey) Relation() string {
	return materialStatusRelation
}

type UpdateMaterialStatusRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaterialStatus]
}
