// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const measureUnitRelation = "public.measure_units"

// MeasureUnit describes an editable measure unit reference entry.
type MeasureUnit struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the measure unit.
	Name string `json:"name" required:"true" maxLen:"250"`
	// Full name of the measure unit.
	NameFull string `json:"name_full" required:"true"`
	// Russian OKEI code used for electronic document matching.
	OkeiCode string `json:"okei_code" maxLen:"4"`
	IsActive bool   `json:"is_active" required:"true"`
}

func (m MeasureUnit) Relation() string {
	return measureUnitRelation
}

func (m MeasureUnit) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MeasureUnitKey is used for detail, update, and delete WHERE clauses.
type MeasureUnitKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MeasureUnitKey) Relation() string {
	return measureUnitRelation
}

type UpdateMeasureUnitRequest struct {
	ID    int
	Input modelbind.ModelInput[*MeasureUnit]
}
