// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const notificationTemplateRelation = "public.notification_templates"

// NotificationTemplate describes an editable notification template unit reference entry.
type NotificationTemplate struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the notification template.
	Code string `json:"code" required:"true" maxLen:"250"`
	// Event name of the template
	Event string `json:"event" required:"true"`
	// Template body
	BodyTemplate string `json:"body_template" required:"true"`
	IsActive     bool   `json:"is_active" required:"true"`
}

func (m NotificationTemplate) Relation() string {
	return notificationTemplateRelation
}

func (m NotificationTemplate) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// NotificationTemplateKey is used for detail, update, and delete WHERE clauses.
type NotificationTemplateKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m NotificationTemplateKey) Relation() string {
	return notificationTemplateRelation
}

type UpdateNotificationTemplateRequest struct {
	ID    int
	Input modelbind.ModelInput[*NotificationTemplate]
}
