// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const orderImportanceRelation = "public.order_importances"

// OrderImportance describes an editable material request importance reference entry.
type OrderImportance struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the importance level.
	Name string `json:"name" required:"true"`
	// Display and priority order.
	SortOrder int `json:"sort_order" required:"true"`
	// Whether the importance level can be selected for new request items.
	IsActive bool `json:"is_active" required:"true"`
}

func (m OrderImportance) Relation() string {
	return orderImportanceRelation
}

func (m OrderImportance) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// OrderImportanceKey is used for detail, update, and delete WHERE clauses.
type OrderImportanceKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m OrderImportanceKey) Relation() string {
	return orderImportanceRelation
}

type UpdateOrderImportanceRequest struct {
	ID    int
	Input modelbind.ModelInput[*OrderImportance]
}
