// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const supplierRelation = "public.suppliers"

// Supplier describes an editable supplier reference entry.
type Supplier struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the supplier.
	Name string `json:"name" required:"true" maxLen:"250"`
	// Full name of the supplier.
	NameFull string `json:"name_full" required:"true"`
	// Supplier inn
	Inn string `json:"inn" required:"true" maxLen:"12"`
	// Supplier kpp
	Kpp      *string `json:"kpp" maxLen:"10"`
	IsActive bool    `json:"is_active" required:"true"`
}

func (m Supplier) Relation() string {
	return supplierRelation
}

func (m Supplier) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// SupplierKey is used for detail, update, and delete WHERE clauses.
type SupplierKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m SupplierKey) Relation() string {
	return supplierRelation
}

type UpdateSupplierRequest struct {
	ID    int
	Input modelbind.ModelInput[*Supplier]
}
