-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.max_users (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	contact_id integer REFERENCES public.contacts(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	max_user_id bigint NOT NULL,
	username text,
	avatar_url text,
	raw_user jsonb NOT NULL,
	raw_user_with_photo jsonb,
	is_active boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.max_users IS 'MAX user reference data.';
COMMENT ON COLUMN public.max_users.contact_id IS 'Contact reference';
COMMENT ON COLUMN public.max_users.max_user_id IS 'MAX user ID';
COMMENT ON COLUMN public.max_users.username IS 'Display name of the MAX user.';
COMMENT ON COLUMN public.max_users.avatar_url IS 'MAX user avatar.';
COMMENT ON COLUMN public.max_users.raw_user IS 'Raw MAX user data.';
COMMENT ON COLUMN public.max_users.raw_user_with_photo IS 'Raw MAX user data containing photo information.';
COMMENT ON COLUMN public.max_users.is_active IS 'Whether the MAX user is active.';

CREATE UNIQUE INDEX max_users_max_user_id_idx
	ON public.max_users USING btree (max_user_id);

CREATE INDEX max_users_contact_id_idx
	ON public.max_users USING btree (contact_id);

WITH required(code, description) AS (
	VALUES
		('maxUser.list', 'Просмотр списка пользователей MAX'),
		('maxUser.detail', 'Просмотр пользователя MAX'),
		('maxUser.update', 'Изменение пользователя MAX'),
		('maxUser.delete', 'Удаление пользователя MAX')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('maxUser.list'),
		('maxUser.detail'),
		('maxUser.update'),
		('maxUser.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'maxUsers',
	'/max-users',
	'Пользователи MAX',
	'Справочники',
	'pi pi-id-card',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Пользователи MAX',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Пользователи MAX'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Пользователи MAX';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Пользователи MAX'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Пользователи MAX',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'maxUsers'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Пользователи MAX'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Пользователи MAX',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Пользователи MAX'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'maxUsers'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);


-- View: public.max_users_list
CREATE OR REPLACE VIEW public.max_users_list AS
SELECT
	u.id,
	CASE WHEN u.contact_id IS NULL THEN NULL ELSE contacts_ref(contacts) END AS contact,
	u.max_user_id,
	u.username,
	u.avatar_url,
	u.raw_user,
	u.is_active
FROM public.max_users AS u
LEFT JOIN public.contacts AS contacts ON contacts.id = u.contact_id;

COMMIT;
