BEGIN;

CREATE TABLE public.ra_materials (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	effective_at timestamptz NOT NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	recorder_type text NOT NULL,
	recorder_id bigint NOT NULL,
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id),
	material_id integer NOT NULL REFERENCES public.materials(id),
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT ra_materials_recorder_type_chk CHECK (btrim(recorder_type) <> ''),
	CONSTRAINT ra_materials_quant_chk CHECK (quant <> 0)
);

COMMENT ON TABLE public.ra_materials IS 'Authoritative immutable action ledger for the materials accumulation register. Positive quant adds stock; negative quant removes stock.';
COMMENT ON COLUMN public.ra_materials.effective_at IS 'Business instant at which the inventory movement takes effect.';
COMMENT ON COLUMN public.ra_materials.created_at IS 'Instant when the register action row was created.';
COMMENT ON COLUMN public.ra_materials.recorder_type IS 'Application-level type/name of the source document or operation that produced the action.';
COMMENT ON COLUMN public.ra_materials.recorder_id IS 'Identifier of the source document or operation that produced the action.';
COMMENT ON COLUMN public.ra_materials.quant IS 'Signed material quantity: positive for receipt, negative for consumption.';

CREATE INDEX ra_materials_recorder_idx
	ON public.ra_materials (recorder_type, recorder_id);

CREATE INDEX ra_materials_effective_at_idx
	ON public.ra_materials (effective_at);

CREATE INDEX ra_materials_balance_idx
	ON public.ra_materials (construction_site_id, material_id, effective_at, id);

CREATE TABLE public.rg_materials_period (
	period_start date NOT NULL,
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id),
	material_id integer NOT NULL REFERENCES public.materials(id),
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT rg_materials_period_pkey PRIMARY KEY (
		construction_site_id,
		material_id,
		period_start
	)
);

COMMENT ON TABLE public.rg_materials_period IS 'Monthly net turnover of the materials register. Rows are period deltas, not cumulative balances.';
COMMENT ON COLUMN public.rg_materials_period.period_start IS 'First local calendar date of the aggregation month in the configured business time zone.';

CREATE INDEX rg_materials_period_start_idx
	ON public.rg_materials_period (period_start);

CREATE TABLE public.rg_materials_current (
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id),
	material_id integer NOT NULL REFERENCES public.materials(id),
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT rg_materials_current_pkey PRIMARY KEY (
		construction_site_id,
		material_id
	)
);

COMMENT ON TABLE public.rg_materials_current IS 'Fast current posted balance of the materials register.';

CREATE OR REPLACE FUNCTION public.rg_materials_apply_delta(
	in_effective_at timestamptz,
	in_construction_site_id integer,
	in_material_id integer,
	in_delta_quant numeric(19, 4)
)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
	v_period_start date;
BEGIN
	IF in_delta_quant = 0 THEN
		RETURN;
	END IF;

	v_period_start := public.register_month_start(in_effective_at);

	INSERT INTO public.rg_materials_period (
		period_start,
		construction_site_id,
		material_id,
		quant
	)
	VALUES (
		v_period_start,
		in_construction_site_id,
		in_material_id,
		in_delta_quant
	)
	ON CONFLICT (construction_site_id, material_id, period_start)
	DO UPDATE
	SET quant = rg_materials_period.quant + EXCLUDED.quant;

	DELETE FROM public.rg_materials_period
	WHERE period_start = v_period_start
		AND construction_site_id = in_construction_site_id
		AND material_id = in_material_id
		AND quant = 0;

	INSERT INTO public.rg_materials_current (
		construction_site_id,
		material_id,
		quant
	)
	VALUES (
		in_construction_site_id,
		in_material_id,
		in_delta_quant
	)
	ON CONFLICT (construction_site_id, material_id)
	DO UPDATE
	SET quant = rg_materials_current.quant + EXCLUDED.quant;

	DELETE FROM public.rg_materials_current
	WHERE construction_site_id = in_construction_site_id
		AND material_id = in_material_id
		AND quant = 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ra_materials_process()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM public.rg_materials_apply_delta(
			NEW.effective_at,
			NEW.construction_site_id,
			NEW.material_id,
			NEW.quant
		);

		RETURN NEW;
	END IF;

	IF TG_OP = 'DELETE' THEN
		PERFORM public.rg_materials_apply_delta(
			OLD.effective_at,
			OLD.construction_site_id,
			OLD.material_id,
			-OLD.quant
		);

		RETURN OLD;
	END IF;

	RAISE EXCEPTION 'Unsupported operation % on ra_materials', TG_OP;
END;
$function$;

CREATE TRIGGER ra_materials_process_trigger
	AFTER INSERT OR DELETE
	ON public.ra_materials
	FOR EACH ROW
	EXECUTE FUNCTION public.ra_materials_process();

CREATE OR REPLACE FUNCTION public.ra_materials_reject_update()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	RAISE EXCEPTION 'ra_materials rows are immutable; delete the old register actions and insert replacement actions instead'
		USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER ra_materials_reject_update_trigger
	BEFORE UPDATE
	ON public.ra_materials
	FOR EACH ROW
	EXECUTE FUNCTION public.ra_materials_reject_update();

CREATE OR REPLACE FUNCTION public.ra_materials_add_act(
	in_effective_at timestamptz,
	in_recorder_type text,
	in_recorder_id bigint,
	in_construction_site_id integer,
	in_material_id integer,
	in_quant numeric(19, 4)
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
	v_id bigint;
BEGIN
	INSERT INTO public.ra_materials (
		effective_at,
		recorder_type,
		recorder_id,
		construction_site_id,
		material_id,
		quant
	)
	VALUES (
		in_effective_at,
		in_recorder_type,
		in_recorder_id,
		in_construction_site_id,
		in_material_id,
		in_quant
	)
	RETURNING id INTO v_id;

	RETURN v_id;
END;
$function$;

COMMENT ON FUNCTION public.ra_materials_add_act(timestamptz, text, bigint, integer, integer, numeric) IS 'Adds one immutable materials register action and returns its action id.';

CREATE OR REPLACE FUNCTION public.ra_materials_remove_acts(
	in_recorder_type text,
	in_recorder_id bigint
)
RETURNS bigint
LANGUAGE sql
AS $function$
	WITH deleted AS (
		DELETE FROM public.ra_materials
		WHERE recorder_type = in_recorder_type
			AND recorder_id = in_recorder_id
		RETURNING 1
	)
	SELECT count(*)::bigint
	FROM deleted;
$function$;

COMMENT ON FUNCTION public.ra_materials_remove_acts(text, bigint) IS 'Removes all materials register actions written by one source recorder and returns the number of removed actions.';

CREATE OR REPLACE FUNCTION public.rg_materials_rebuild()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
	TRUNCATE TABLE public.rg_materials_period, public.rg_materials_current;

	INSERT INTO public.rg_materials_period (
		period_start,
		construction_site_id,
		material_id,
		quant
	)
	SELECT
		public.register_month_start(action.effective_at),
		action.construction_site_id,
		action.material_id,
		SUM(action.quant)::numeric(19, 4)
	FROM public.ra_materials AS action
	GROUP BY
		public.register_month_start(action.effective_at),
		action.construction_site_id,
		action.material_id
	HAVING SUM(action.quant) <> 0;

	INSERT INTO public.rg_materials_current (
		construction_site_id,
		material_id,
		quant
	)
	SELECT
		action.construction_site_id,
		action.material_id,
		SUM(action.quant)::numeric(19, 4)
	FROM public.ra_materials AS action
	GROUP BY
		action.construction_site_id,
		action.material_id
	HAVING SUM(action.quant) <> 0;
END;
$function$;

COMMENT ON FUNCTION public.rg_materials_rebuild() IS 'Rebuilds all materials register aggregates from the authoritative ra_materials ledger. Run after changing register_settings.business_timezone.';

CREATE OR REPLACE FUNCTION public.rg_materials_balance(
	in_construction_site_ids integer[] DEFAULT NULL,
	in_material_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	construction_site_id integer,
	material_id integer,
	quant numeric(19, 4)
)
LANGUAGE sql
STABLE
AS $function$
	SELECT
		balance.construction_site_id,
		balance.material_id,
		balance.quant
	FROM public.rg_materials_current AS balance
	WHERE (
		in_construction_site_ids IS NULL
		OR cardinality(in_construction_site_ids) = 0
		OR balance.construction_site_id = ANY(in_construction_site_ids)
	)
	AND (
		in_material_ids IS NULL
		OR cardinality(in_material_ids) = 0
		OR balance.material_id = ANY(in_material_ids)
	)
	AND balance.quant <> 0
	ORDER BY
		balance.construction_site_id,
		balance.material_id;
$function$;

COMMENT ON FUNCTION public.rg_materials_balance(integer[], integer[]) IS 'Returns the fast current posted balance of the materials register.';

CREATE OR REPLACE FUNCTION public.rg_materials_balance(
	in_effective_at timestamptz,
	in_construction_site_ids integer[] DEFAULT NULL,
	in_material_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	construction_site_id integer,
	material_id integer,
	quant numeric(19, 4)
)
LANGUAGE sql
STABLE
AS $function$
	WITH boundary AS (
		SELECT
			public.register_month_start(in_effective_at) AS period_start,
			public.register_month_start_at(in_effective_at) AS period_start_at
	), movements AS (
		SELECT
			period.construction_site_id,
			period.material_id,
			period.quant
		FROM public.rg_materials_period AS period
		CROSS JOIN boundary
		WHERE period.period_start < boundary.period_start
			AND (
				in_construction_site_ids IS NULL
				OR cardinality(in_construction_site_ids) = 0
				OR period.construction_site_id = ANY(in_construction_site_ids)
			)
			AND (
				in_material_ids IS NULL
				OR cardinality(in_material_ids) = 0
				OR period.material_id = ANY(in_material_ids)
			)

		UNION ALL

		SELECT
			action.construction_site_id,
			action.material_id,
			action.quant
		FROM public.ra_materials AS action
		CROSS JOIN boundary
		WHERE action.effective_at >= boundary.period_start_at
			AND action.effective_at <= in_effective_at
			AND (
				in_construction_site_ids IS NULL
				OR cardinality(in_construction_site_ids) = 0
				OR action.construction_site_id = ANY(in_construction_site_ids)
			)
			AND (
				in_material_ids IS NULL
				OR cardinality(in_material_ids) = 0
				OR action.material_id = ANY(in_material_ids)
			)
	)
	SELECT
		movements.construction_site_id,
		movements.material_id,
		SUM(movements.quant)::numeric(19, 4) AS quant
	FROM movements
	GROUP BY
		movements.construction_site_id,
		movements.material_id
	HAVING SUM(movements.quant) <> 0
	ORDER BY
		movements.construction_site_id,
		movements.material_id;
$function$;

COMMENT ON FUNCTION public.rg_materials_balance(timestamptz, integer[], integer[]) IS 'Returns materials balance at an exact instant using completed monthly turnovers plus raw actions from the requested month.';

COMMIT;
