-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.main_menus AS menu
USING public.application_routes AS route
WHERE menu.route_id = route.id
	AND menu.role_id = 'admin'
	AND menu.user_id IS NULL
	AND menu.caption = 'Контакты'
	AND route.name = 'contacts';

DELETE FROM public.main_menus AS parent
WHERE parent.role_id = 'admin'
	AND parent.user_id IS NULL
	AND parent.parent_id IS NULL
	AND parent.caption = 'Контакты'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS child
		WHERE child.parent_id = parent.id
	);

DELETE FROM public.application_routes AS route
WHERE route.name = 'contacts'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS menu
		WHERE menu.route_id = route.id
	);

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'contact.create',
	'contact.list',
	'contact.detail',
	'contact.update',
	'contact.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'contact.create',
	'contact.list',
	'contact.detail',
	'contact.update',
	'contact.delete'
);

DROP TRIGGER IF EXISTS contacts_trigger_before ON public.contacts;
DROP FUNCTION IF EXISTS public.contacts_process();
DROP FUNCTION IF EXISTS public.contacts_ref(public.contacts);
DROP FUNCTION IF EXISTS public.format_phone(text);
DROP TABLE IF EXISTS public.contacts;

COMMIT;
