-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.material_transfer_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	material_transfer_id integer NOT NULL REFERENCES public.material_transfers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quant numeric(19, 4) NOT NULL,
	CHECK (line_num > 0),
	CHECK (quant > 0)
);

COMMENT ON TABLE public.material_transfer_items IS 'Material transfer document lines.';
COMMENT ON COLUMN public.material_transfer_items.line_num IS 'Line number within the document.';
COMMENT ON COLUMN public.material_transfer_items.material_transfer_id IS 'Parent material transfer document.';
COMMENT ON COLUMN public.material_transfer_items.material_id IS 'Material.';
COMMENT ON COLUMN public.material_transfer_items.measure_unit_id IS 'Measurement unit.';
COMMENT ON COLUMN public.material_transfer_items.quant IS 'Material quantity.';

CREATE UNIQUE INDEX material_transfer_items_material_transfer_id_line_num_idx
	ON public.material_transfer_items USING btree (material_transfer_id, line_num);

WITH required(code, description) AS (
	VALUES
		('materialTransferItem.create', 'Создание строки перемещения материалов'),
		('materialTransferItem.list', 'Просмотр строк перемещения материалов'),
		('materialTransferItem.detail', 'Просмотр строки перемещения материалов'),
		('materialTransferItem.update', 'Изменение строки перемещения материалов'),
		('materialTransferItem.delete', 'Удаление строки перемещения материалов')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialTransferItem.create'),
		('materialTransferItem.list'),
		('materialTransferItem.detail'),
		('materialTransferItem.update'),
		('materialTransferItem.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

COMMIT;
