-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.suppliers (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name varchar(250) NOT NULL,
	name_full text NOT NULL,
	inn varchar(12),
	kpp varchar(10),
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> '')
);

COMMENT ON TABLE public.suppliers IS 'Supplier reference data.';
COMMENT ON COLUMN public.suppliers.name IS 'Display name of the supplier.';
COMMENT ON COLUMN public.suppliers.name_full IS 'Full name of the supplier.';
COMMENT ON COLUMN public.suppliers.inn IS 'Supplier inn';
COMMENT ON COLUMN public.suppliers.kpp IS 'Supplier kpp';

CREATE INDEX suppliers_name_idx
	ON public.suppliers USING btree (lower(name));

CREATE INDEX suppliers_inn_idx
	ON public.suppliers USING btree (inn);

WITH required(code, description) AS (
	VALUES
		('supplier.create', 'Создание поставщика'),
		('supplier.list', 'Просмотр списка поставщиков'),
		('supplier.detail', 'Просмотр поставщика'),
		('supplier.update', 'Изменение поставщика'),
		('supplier.delete', 'Удаление поставщика')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('supplier.create'),
		('supplier.list'),
		('supplier.detail'),
		('supplier.update'),
		('supplier.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'suppliers',
	'/supplier',
	'Поставщики',
	'Справочники',
	'pi pi-car',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Поставщики',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Поставщики'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Поставщики';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Поставщики'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Поставщики',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'suppliers'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Поставщики'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Поставщики',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Поставщики'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'suppliers'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
