BEGIN;

CREATE TABLE public.order_importances (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name text NOT NULL,
	sort_order integer NOT NULL DEFAULT 0,
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> ''),
	CHECK (sort_order >= 0)
);

COMMENT ON TABLE public.order_importances IS 'Material request importance reference data.';
COMMENT ON COLUMN public.order_importances.name IS 'Display name of the importance level.';
COMMENT ON COLUMN public.order_importances.sort_order IS 'Display and priority order.';
COMMENT ON COLUMN public.order_importances.is_active IS 'Whether the importance level can be selected for new request items.';

CREATE UNIQUE INDEX order_importances_name_idx
	ON public.order_importances USING btree (lower(name));

CREATE INDEX order_importances_sort_order_idx
	ON public.order_importances USING btree (sort_order);

CREATE TABLE public.material_request_statuses (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	code varchar(40) NOT NULL,
	name text NOT NULL,
	CHECK (btrim(code) <> ''),
	CHECK (btrim(name) <> ''),
	CHECK (code IN ('draft', 'submitted', 'in_progress', 'completed', 'cancelled'))
);

COMMENT ON TABLE public.material_request_statuses IS 'Material request item status reference data.';
COMMENT ON COLUMN public.material_request_statuses.code IS 'Stable status code used by the material request workflow.';
COMMENT ON COLUMN public.material_request_statuses.name IS 'Display name of the status.';

CREATE UNIQUE INDEX material_request_statuses_code_idx
	ON public.material_request_statuses USING btree (code);

CREATE UNIQUE INDEX material_request_statuses_name_idx
	ON public.material_request_statuses USING btree (lower(name));

INSERT INTO public.material_request_statuses (id, code, name)
VALUES
	(1, 'draft', 'Черновик'),
	(2, 'submitted', 'Отправлена'),
	(3, 'in_progress', 'В работе'),
	(4, 'completed', 'Выполнена'),
	(5, 'cancelled', 'Отменена');

SELECT setval(
	pg_get_serial_sequence('public.material_request_statuses', 'id'),
	(SELECT MAX(id) FROM public.material_request_statuses),
	true
);

CREATE TABLE public.material_requests (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	date timestamp with time zone NOT NULL DEFAULT now(),
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	construction_manager_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	comment text,
	version bigint NOT NULL DEFAULT 1,
	CHECK (version > 0)
);

COMMENT ON TABLE public.material_requests IS 'Material request document headers.';
COMMENT ON COLUMN public.material_requests.date IS 'Document date and time.';
COMMENT ON COLUMN public.material_requests.construction_site_id IS 'Construction site requesting the materials.';
COMMENT ON COLUMN public.material_requests.construction_manager_id IS 'Manager responsible for the material request.';
COMMENT ON COLUMN public.material_requests.comment IS 'Optional document comment.';
COMMENT ON COLUMN public.material_requests.version IS 'Optimistic concurrency version.';

CREATE INDEX material_requests_construction_site_id_idx
	ON public.material_requests USING btree (construction_site_id);

CREATE INDEX material_requests_construction_manager_id_idx
	ON public.material_requests USING btree (construction_manager_id);

CREATE INDEX material_requests_date_idx
	ON public.material_requests USING btree (date);

CREATE TABLE public.material_request_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	material_request_id integer NOT NULL REFERENCES public.material_requests(id) ON DELETE CASCADE ON UPDATE CASCADE,
	material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quant numeric(19, 4) NOT NULL,
	supplier_id integer REFERENCES public.suppliers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	required_date date,
	order_importance_id integer NOT NULL REFERENCES public.order_importances(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	status_id integer NOT NULL DEFAULT 1 REFERENCES public.material_request_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CHECK (line_num > 0),
	CHECK (quant > 0)
);

COMMENT ON TABLE public.material_request_items IS 'Material request document lines.';
COMMENT ON COLUMN public.material_request_items.line_num IS 'Line number within the document.';
COMMENT ON COLUMN public.material_request_items.material_request_id IS 'Parent material request document.';
COMMENT ON COLUMN public.material_request_items.material_id IS 'Requested material.';
COMMENT ON COLUMN public.material_request_items.measure_unit_id IS 'Measurement unit copied from the selected material.';
COMMENT ON COLUMN public.material_request_items.quant IS 'Requested quantity.';
COMMENT ON COLUMN public.material_request_items.supplier_id IS 'Optional supplier assigned by a supply user.';
COMMENT ON COLUMN public.material_request_items.required_date IS 'Optional date by which the material is required.';
COMMENT ON COLUMN public.material_request_items.order_importance_id IS 'Request importance level.';
COMMENT ON COLUMN public.material_request_items.status_id IS 'Request item workflow status; new lines start in draft status.';

CREATE UNIQUE INDEX material_request_items_request_line_idx
	ON public.material_request_items USING btree (material_request_id, line_num);

CREATE INDEX material_request_items_material_id_idx
	ON public.material_request_items USING btree (material_id);

CREATE INDEX material_request_items_supplier_id_idx
	ON public.material_request_items USING btree (supplier_id);

CREATE INDEX material_request_items_importance_id_idx
	ON public.material_request_items USING btree (order_importance_id);

CREATE INDEX material_request_items_status_id_idx
	ON public.material_request_items USING btree (status_id);

CREATE INDEX material_request_items_required_date_idx
	ON public.material_request_items USING btree (required_date);

CREATE OR REPLACE FUNCTION public.order_importances_ref(public.order_importances)
RETURNS json AS
$function$
	SELECT CASE WHEN $1.id IS NULL THEN NULL ELSE json_build_object(
		'keys', json_build_object('id', $1.id),
		'descr', $1.name,
		'dataType', 'orderImportances'
	) END;
$function$
LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.material_request_statuses_ref(public.material_request_statuses)
RETURNS json AS
$function$
	SELECT CASE WHEN $1.id IS NULL THEN NULL ELSE json_build_object(
		'keys', json_build_object('id', $1.id),
		'descr', $1.name,
		'dataType', 'materialRequestStatuses'
	) END;
$function$
LANGUAGE sql STABLE;

CREATE OR REPLACE VIEW public.material_requests_list AS
SELECT
	request.id,
	request.date,
	request.construction_site_id,
	request.construction_manager_id,
	request.comment,
	request.version,
	public.construction_sites_ref(site) AS construction_site,
	public.users_ref(manager) AS construction_manager
FROM public.material_requests AS request
LEFT JOIN public.construction_sites AS site ON site.id = request.construction_site_id
LEFT JOIN public.users AS manager ON manager.id = request.construction_manager_id;

CREATE OR REPLACE VIEW public.material_request_items_list AS
SELECT
	item.id,
	item.line_num,
	item.material_request_id,
	item.material_id,
	item.measure_unit_id,
	item.quant,
	item.supplier_id,
	item.required_date,
	item.order_importance_id,
	item.status_id,
	public.materials_ref(material) AS material,
	public.measure_units_ref(measure_unit) AS measure_unit,
	public.suppliers_ref(supplier) AS supplier,
	public.order_importances_ref(importance) AS order_importance,
	public.material_request_statuses_ref(status) AS status
FROM public.material_request_items AS item
LEFT JOIN public.materials AS material ON material.id = item.material_id
LEFT JOIN public.measure_units AS measure_unit ON measure_unit.id = item.measure_unit_id
LEFT JOIN public.suppliers AS supplier ON supplier.id = item.supplier_id
LEFT JOIN public.order_importances AS importance ON importance.id = item.order_importance_id
LEFT JOIN public.material_request_statuses AS status ON status.id = item.status_id;

WITH required(code, description) AS (
	VALUES
		('orderImportance.create', 'Создание важности заявки на материалы'),
		('orderImportance.list', 'Просмотр списка важности заявок на материалы'),
		('orderImportance.detail', 'Просмотр важности заявки на материалы'),
		('orderImportance.update', 'Изменение важности заявки на материалы'),
		('orderImportance.delete', 'Удаление важности заявки на материалы'),
		('materialRequestStatus.list', 'Просмотр списка статусов заявок на материалы'),
		('materialRequestStatus.detail', 'Просмотр статуса заявки на материалы'),
		('materialRequestStatus.update', 'Изменение статуса заявки на материалы'),
		('materialRequest.create', 'Создание заявки на материалы'),
		('materialRequest.list', 'Просмотр списка заявок на материалы'),
		('materialRequest.detail', 'Просмотр заявки на материалы'),
		('materialRequest.update', 'Изменение заявки на материалы'),
		('materialRequest.delete', 'Удаление заявки на материалы'),
		('materialRequest.submit', 'Отправка заявки на материалы'),
		('materialRequestItem.create', 'Создание строки заявки на материалы'),
		('materialRequestItem.list', 'Просмотр строк заявки на материалы'),
		('materialRequestItem.detail', 'Просмотр строки заявки на материалы'),
		('materialRequestItem.update', 'Изменение строки заявки на материалы'),
		('materialRequestItem.delete', 'Удаление строки заявки на материалы')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH required(permission_code) AS (
	VALUES
		('orderImportance.create'),
		('orderImportance.list'),
		('orderImportance.detail'),
		('orderImportance.update'),
		('orderImportance.delete'),
		('materialRequestStatus.list'),
		('materialRequestStatus.detail'),
		('materialRequestStatus.update'),
		('materialRequest.create'),
		('materialRequest.list'),
		('materialRequest.detail'),
		('materialRequest.update'),
		('materialRequest.delete'),
		('materialRequest.submit'),
		('materialRequestItem.create'),
		('materialRequestItem.list'),
		('materialRequestItem.detail'),
		('materialRequestItem.update'),
		('materialRequestItem.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'admin'::public.role_types, required.permission_code
FROM required
ON CONFLICT DO NOTHING;

WITH required(permission_code) AS (
	VALUES
		('constructionSite.list'),
		('constructionSite.detail'),
		('material.list'),
		('material.detail'),
		('measureUnit.list'),
		('measureUnit.detail'),
		('orderImportance.list'),
		('orderImportance.detail'),
		('materialRequestStatus.list'),
		('materialRequestStatus.detail'),
		('materialRequest.create'),
		('materialRequest.list'),
		('materialRequest.detail'),
		('materialRequest.update'),
		('materialRequest.delete'),
		('materialRequest.submit')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'construction_site_manager'::public.role_types, required.permission_code
FROM required
ON CONFLICT DO NOTHING;

WITH required(permission_code) AS (
	VALUES
		('supplier.list'),
		('supplier.detail'),
		('material.list'),
		('material.detail'),
		('measureUnit.list'),
		('measureUnit.detail'),
		('orderImportance.list'),
		('orderImportance.detail'),
		('materialRequestStatus.list'),
		('materialRequestStatus.detail'),
		('materialRequest.list'),
		('materialRequest.detail'),
		('materialRequest.update')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'supplier'::public.role_types, required.permission_code
FROM required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES
	('orderImportances', '/order-importances', 'Важность заявок', 'Справочники', 'pi pi-sort-amount-down', true, true),
	('materialRequestStatuses', '/material-request-statuses', 'Статусы заявок', 'Справочники', 'pi pi-tags', true, true),
	('materialRequests', '/material-requests', 'Заявки на материалы', 'Документы', 'pi pi-clipboard', true, true)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.section,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types),
		('construction_site_manager'::public.role_types),
		('supplier'::public.role_types)
)
INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT roles.role_id, 'Материалы', NULL, 40, true
FROM roles
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = roles.role_id
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Материалы'
);

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types),
		('construction_site_manager'::public.role_types),
		('supplier'::public.role_types)
)
INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	roles.role_id,
	parent.id,
	'Заявки на материалы',
	route.id,
	NULL,
	40,
	true
FROM roles
JOIN public.application_routes AS route ON route.name = 'materialRequests'
JOIN LATERAL (
	SELECT menu.id
	FROM public.main_menus AS menu
	WHERE menu.role_id = roles.role_id
		AND menu.user_id IS NULL
		AND menu.parent_id IS NULL
		AND menu.caption = 'Материалы'
	ORDER BY menu.id
	LIMIT 1
) AS parent ON true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = roles.role_id
		AND existing.user_id IS NULL
		AND existing.route_id = route.id
);

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT 'admin'::public.role_types, 'Заявки на материалы', NULL, 45, true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Заявки на материалы'
);

WITH routes(route_name, caption, sort_order) AS (
	VALUES
		('materialRequestStatuses', 'Статусы заявок', 10),
		('orderImportances', 'Важность заявок', 20)
)
INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	routes.caption,
	application_route.id,
	NULL,
	routes.sort_order,
	true
FROM routes
JOIN public.application_routes AS application_route
	ON application_route.name = routes.route_name
JOIN LATERAL (
	SELECT menu.id
	FROM public.main_menus AS menu
	WHERE menu.role_id = 'admin'::public.role_types
		AND menu.user_id IS NULL
		AND menu.parent_id IS NULL
		AND menu.caption = 'Заявки на материалы'
	ORDER BY menu.id
	LIMIT 1
) AS parent ON true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.route_id = application_route.id
);

WITH aliases(table_name, column_name, column_alias) AS (
	VALUES
		('order_importances', 'id', 'Идентификатор'),
		('order_importances', 'name', 'Наименование'),
		('order_importances', 'sort_order', 'Порядок'),
		('order_importances', 'is_active', 'Активна'),
		('material_request_statuses', 'id', 'Идентификатор'),
		('material_request_statuses', 'code', 'Код'),
		('material_request_statuses', 'name', 'Наименование'),
		('material_requests', 'id', 'Идентификатор'),
		('material_requests', 'date', 'Дата и время'),
		('material_requests', 'construction_site_id', 'Объект строительства'),
		('material_requests', 'construction_manager_id', 'Ответственный прораб'),
		('material_requests', 'comment', 'Комментарий'),
		('material_requests', 'version', 'Версия'),
		('material_request_items', 'id', 'Идентификатор'),
		('material_request_items', 'line_num', 'Номер строки'),
		('material_request_items', 'material_request_id', 'Заявка на материалы'),
		('material_request_items', 'material_id', 'Материал'),
		('material_request_items', 'measure_unit_id', 'Единица измерения'),
		('material_request_items', 'quant', 'Количество'),
		('material_request_items', 'supplier_id', 'Поставщик'),
		('material_request_items', 'required_date', 'Требуемая дата'),
		('material_request_items', 'order_importance_id', 'Важность'),
		('material_request_items', 'status_id', 'Статус')
)
INSERT INTO public.audit_column_aliases (
	table_name,
	column_name,
	column_alias,
	is_active
)
SELECT aliases.table_name, aliases.column_name, aliases.column_alias, true
FROM aliases
ON CONFLICT (table_name, column_name) DO UPDATE
SET
	column_alias = EXCLUDED.column_alias,
	is_active = true;

CREATE TRIGGER audit_log_order_importances
AFTER INSERT OR UPDATE OR DELETE ON public.order_importances
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

CREATE TRIGGER audit_log_material_request_statuses
AFTER INSERT OR UPDATE OR DELETE ON public.material_request_statuses
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

CREATE TRIGGER audit_log_material_requests
AFTER INSERT OR UPDATE OR DELETE ON public.material_requests
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

CREATE TRIGGER audit_log_material_request_items
AFTER INSERT OR UPDATE OR DELETE ON public.material_request_items
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

COMMIT;
