BEGIN;

CREATE TABLE public.user_construction_sites (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE public.user_construction_sites IS 'Construction sites assigned to an application user.';
COMMENT ON COLUMN public.user_construction_sites.user_id IS 'Application user.';
COMMENT ON COLUMN public.user_construction_sites.construction_site_id IS 'Construction site assigned to the user.';

CREATE UNIQUE INDEX user_construction_sites_user_site_idx
	ON public.user_construction_sites USING btree (user_id, construction_site_id);

CREATE INDEX user_construction_sites_construction_site_id_idx
	ON public.user_construction_sites USING btree (construction_site_id);

COMMIT;
