-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.notification_templates (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	code text NOT NULL,
	event text NOT NULL,
	body_template text NOT NULL,
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(code) <> '')
);

COMMENT ON TABLE public.notification_templates IS 'Notification template reference data.';
COMMENT ON COLUMN public.notification_templates.code IS 'Display name of the notification template.';
COMMENT ON COLUMN public.notification_templates.event IS 'Event name of the template';
COMMENT ON COLUMN public.notification_templates.body_template IS 'Template body';

CREATE INDEX notification_templates_code_idx
	ON public.notification_templates USING btree (lower(code));

WITH required(code, description) AS (
	VALUES
		('notificationTemplate.create', 'Создание шаблона уведомления'),
		('notificationTemplate.list', 'Просмотр списка шаблонов уведомления'),
		('notificationTemplate.detail', 'Просмотр шаблона уведомления'),
		('notificationTemplate.update', 'Изменение шаблона уведомления'),
		('notificationTemplate.delete', 'Удаление шаблона уведомления')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('notificationTemplate.create'),
		('notificationTemplate.list'),
		('notificationTemplate.detail'),
		('notificationTemplate.update'),
		('notificationTemplate.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'notificationTemplates',
	'/notification_template',
	'Шаблоны уведомлений',
	'Справочники',
	'pi pi-megaphone',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Шаблоны уведомлений',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Шаблоны уведомлений'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Шаблоны уведомлений';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Шаблоны уведомлений'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Шаблоны уведомлений',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'notificationTemplates'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Шаблоны уведомлений'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Шаблоны уведомлений',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Шаблоны уведомлений'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'notificationTemplates'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
