BEGIN;

ALTER TABLE public.register_settings
	ADD COLUMN materials_allow_negative_open_period boolean NOT NULL DEFAULT true,
	ADD COLUMN materials_exclude_vat_from_cost boolean NOT NULL DEFAULT true,
	ADD COLUMN materials_closed_through date;

COMMENT ON COLUMN public.register_settings.materials_allow_negative_open_period IS
	'Allows material quantity to become negative in an open period. Monetary valuation remains pending until deterministic replay can price the shortage.';
COMMENT ON COLUMN public.register_settings.materials_exclude_vat_from_cost IS
	'Initialization-time material valuation basis. When true, recoverable VAT is excluded from receipt acquisition cost.';
COMMENT ON COLUMN public.register_settings.materials_closed_through IS
	'Inclusive local business date through which material inventory accounting is closed.';

CREATE OR REPLACE FUNCTION public.register_settings_validate()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	BEGIN
		PERFORM timezone(NEW.business_timezone, CURRENT_TIMESTAMP);
	EXCEPTION
		WHEN invalid_parameter_value THEN
			RAISE EXCEPTION 'Invalid PostgreSQL time zone: %', NEW.business_timezone
				USING ERRCODE = '22023';
	END;

	IF TG_OP = 'UPDATE'
		AND NEW.materials_exclude_vat_from_cost IS DISTINCT FROM OLD.materials_exclude_vat_from_cost
		AND EXISTS (SELECT 1 FROM public.ra_materials LIMIT 1)
	THEN
		RAISE EXCEPTION 'Material VAT valuation basis can only be changed before the first material register movement'
			USING ERRCODE = '55000';
	END IF;

	RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS register_settings_validate_trigger ON public.register_settings;
CREATE TRIGGER register_settings_validate_trigger
	BEFORE INSERT OR UPDATE
	ON public.register_settings
	FOR EACH ROW
	EXECUTE FUNCTION public.register_settings_validate();

ALTER TABLE public.ra_materials
	ADD COLUMN recorder_item_id bigint,
	ADD COLUMN movement_order smallint NOT NULL DEFAULT 1,
	ADD COLUMN source_amount numeric(19, 4),
	ADD COLUMN amount numeric(19, 4),
	ADD COLUMN amount_pending boolean NOT NULL DEFAULT false;

ALTER TABLE public.ra_materials
	ADD CONSTRAINT ra_materials_movement_order_chk CHECK (movement_order > 0),
	ADD CONSTRAINT ra_materials_source_amount_chk CHECK (source_amount IS NULL OR source_amount >= 0);

COMMENT ON COLUMN public.ra_materials.recorder_item_id IS
	'Identifier of the source document line. Transfer source and destination movements share the same recorder_item_id.';
COMMENT ON COLUMN public.ra_materials.movement_order IS
	'Deterministic order of movements generated by one recorder line; transfer source is 1 and destination is 2.';
COMMENT ON COLUMN public.ra_materials.source_amount IS
	'Fixed acquisition amount for externally valued incoming movements. NULL for movements whose value is derived by replay.';
COMMENT ON COLUMN public.ra_materials.amount IS
	'Signed calculated movement value. Positive values add inventory value; negative values remove inventory value.';
COMMENT ON COLUMN public.ra_materials.amount_pending IS
	'True when the movement cannot yet be valued because its cost depends on unresolved negative inventory or an unresolved transfer source.';

CREATE INDEX ra_materials_valuation_order_idx
	ON public.ra_materials (
		material_id,
		effective_at,
		recorder_type,
		recorder_id,
		recorder_item_id,
		movement_order,
		id
	);

ALTER TABLE public.rg_materials_period
	ADD COLUMN amount numeric(19, 4),
	ADD COLUMN pending_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.rg_materials_current
	ADD COLUMN amount numeric(19, 4),
	ADD COLUMN pending_count integer NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.rg_materials_period.amount IS
	'Net monetary turnover for the period. NULL when at least one movement in the aggregate is still pending valuation.';
COMMENT ON COLUMN public.rg_materials_current.amount IS
	'Current material inventory value. NULL while the balance contains unresolved monetary valuation.';
COMMENT ON COLUMN public.rg_materials_current.pending_count IS
	'Number of unresolved register actions contributing to the current history.';

CREATE TABLE public.material_valuation_closures (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	closed_through date NOT NULL,
	closed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	closed_by integer REFERENCES public.users(id),
	reopened_at timestamptz,
	reopened_by integer REFERENCES public.users(id),
	CONSTRAINT material_valuation_closures_reopen_chk CHECK (
		(reopened_at IS NULL AND reopened_by IS NULL)
		OR reopened_at IS NOT NULL
	)
);

CREATE INDEX material_valuation_closures_closed_through_idx
	ON public.material_valuation_closures (closed_through, id DESC);

CREATE TABLE public.material_valuation_snapshots (
	closure_id bigint NOT NULL REFERENCES public.material_valuation_closures(id) ON DELETE CASCADE,
	construction_site_id integer NOT NULL REFERENCES public.construction_sites(id),
	material_id integer NOT NULL REFERENCES public.materials(id),
	quant numeric(19, 4) NOT NULL,
	amount numeric(19, 4) NOT NULL,
	CONSTRAINT material_valuation_snapshots_pkey PRIMARY KEY (
		closure_id,
		construction_site_id,
		material_id
	)
);

COMMENT ON TABLE public.material_valuation_closures IS
	'Audit history of material inventory closing operations. Reopening marks the latest active closure but does not delete it.';
COMMENT ON TABLE public.material_valuation_snapshots IS
	'Quantity and monetary balances frozen at each material inventory close.';

CREATE OR REPLACE FUNCTION public.materials_assert_open_date(in_effective_at timestamptz)
RETURNS void
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
	v_closed_through date;
	v_effective_date date;
BEGIN
	SELECT materials_closed_through
	INTO v_closed_through
	FROM public.register_settings
	WHERE id = 1;

	IF v_closed_through IS NULL THEN
		RETURN;
	END IF;

	v_effective_date := (in_effective_at AT TIME ZONE public.register_business_timezone())::date;
	IF v_effective_date <= v_closed_through THEN
		RAISE EXCEPTION 'Material accounting is closed through %, movement date % is locked',
			v_closed_through,
			v_effective_date
			USING ERRCODE = '55000';
	END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.material_document_closed_period_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM public.materials_assert_open_date(NEW.date);
		RETURN NEW;
	END IF;

	IF TG_OP = 'UPDATE' THEN
		PERFORM public.materials_assert_open_date(OLD.date);
		PERFORM public.materials_assert_open_date(NEW.date);
		RETURN NEW;
	END IF;

	PERFORM public.materials_assert_open_date(OLD.date);
	RETURN OLD;
END;
$function$;

CREATE TRIGGER material_receipts_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_receipts
	FOR EACH ROW EXECUTE FUNCTION public.material_document_closed_period_guard();
CREATE TRIGGER material_consumptions_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_consumptions
	FOR EACH ROW EXECUTE FUNCTION public.material_document_closed_period_guard();
CREATE TRIGGER material_transfers_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_transfers
	FOR EACH ROW EXECUTE FUNCTION public.material_document_closed_period_guard();

CREATE OR REPLACE FUNCTION public.material_document_item_closed_period_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
	v_document_id integer;
	v_effective_at timestamptz;
BEGIN
	IF TG_TABLE_NAME = 'material_receipt_items' THEN
		v_document_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.material_receipt_id ELSE NEW.material_receipt_id END;
		SELECT date INTO v_effective_at FROM public.material_receipts WHERE id = v_document_id;
	ELSIF TG_TABLE_NAME = 'material_consumption_items' THEN
		v_document_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.material_consumption_id ELSE NEW.material_consumption_id END;
		SELECT date INTO v_effective_at FROM public.material_consumptions WHERE id = v_document_id;
	ELSIF TG_TABLE_NAME = 'material_transfer_items' THEN
		v_document_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.material_transfer_id ELSE NEW.material_transfer_id END;
		SELECT date INTO v_effective_at FROM public.material_transfers WHERE id = v_document_id;
	END IF;

	IF v_effective_at IS NOT NULL THEN
		PERFORM public.materials_assert_open_date(v_effective_at);
	END IF;

	RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$function$;

CREATE TRIGGER material_receipt_items_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_receipt_items
	FOR EACH ROW EXECUTE FUNCTION public.material_document_item_closed_period_guard();
CREATE TRIGGER material_consumption_items_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_consumption_items
	FOR EACH ROW EXECUTE FUNCTION public.material_document_item_closed_period_guard();
CREATE TRIGGER material_transfer_items_closed_period_guard_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON public.material_transfer_items
	FOR EACH ROW EXECUTE FUNCTION public.material_document_item_closed_period_guard();

CREATE OR REPLACE FUNCTION public.ra_materials_closed_period_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM public.materials_assert_open_date(NEW.effective_at);
		RETURN NEW;
	END IF;

	IF TG_OP = 'DELETE' THEN
		PERFORM public.materials_assert_open_date(OLD.effective_at);
		RETURN OLD;
	END IF;

	RETURN NEW;
END;
$function$;

CREATE TRIGGER ra_materials_closed_period_guard_trigger
	BEFORE INSERT OR DELETE
	ON public.ra_materials
	FOR EACH ROW
	EXECUTE FUNCTION public.ra_materials_closed_period_guard();

CREATE OR REPLACE FUNCTION public.ra_materials_reject_update()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF current_setting('skstruktura.material_valuation_internal', true) = 'on'
		AND NEW.id = OLD.id
		AND NEW.effective_at = OLD.effective_at
		AND NEW.created_at = OLD.created_at
		AND NEW.recorder_type = OLD.recorder_type
		AND NEW.recorder_id = OLD.recorder_id
		AND NEW.construction_site_id = OLD.construction_site_id
		AND NEW.material_id = OLD.material_id
		AND NEW.quant = OLD.quant
		AND NEW.recorder_item_id IS NOT DISTINCT FROM OLD.recorder_item_id
		AND NEW.movement_order = OLD.movement_order
		AND NEW.source_amount IS NOT DISTINCT FROM OLD.source_amount
	THEN
		RETURN NEW;
	END IF;

	RAISE EXCEPTION 'ra_materials quantity/source rows are immutable; delete the old register actions and insert replacement actions instead'
		USING ERRCODE = '55000';
END;
$function$;

CREATE OR REPLACE FUNCTION public.rg_materials_apply_delta(
	in_effective_at timestamptz,
	in_construction_site_id integer,
	in_material_id integer,
	in_delta_quant numeric(19, 4),
	in_delta_amount numeric(19, 4),
	in_pending_delta integer
)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
	v_period_start date;
BEGIN
	IF in_delta_quant = 0 AND COALESCE(in_delta_amount, 0) = 0 AND in_pending_delta = 0 THEN
		RETURN;
	END IF;

	v_period_start := public.register_month_start(in_effective_at);

	INSERT INTO public.rg_materials_period (
		period_start,
		construction_site_id,
		material_id,
		quant,
		amount,
		pending_count
	)
	VALUES (
		v_period_start,
		in_construction_site_id,
		in_material_id,
		in_delta_quant,
		CASE WHEN in_pending_delta > 0 THEN NULL ELSE COALESCE(in_delta_amount, 0) END,
		GREATEST(in_pending_delta, 0)
	)
	ON CONFLICT (construction_site_id, material_id, period_start)
	DO UPDATE
	SET
		quant = rg_materials_period.quant + EXCLUDED.quant,
		pending_count = rg_materials_period.pending_count + in_pending_delta,
		amount = CASE
			WHEN rg_materials_period.pending_count + in_pending_delta > 0 THEN NULL
			ELSE COALESCE(rg_materials_period.amount, 0) + COALESCE(in_delta_amount, 0)
		END;

	DELETE FROM public.rg_materials_period
	WHERE period_start = v_period_start
		AND construction_site_id = in_construction_site_id
		AND material_id = in_material_id
		AND quant = 0
		AND pending_count = 0
		AND COALESCE(amount, 0) = 0;

	INSERT INTO public.rg_materials_current (
		construction_site_id,
		material_id,
		quant,
		amount,
		pending_count
	)
	VALUES (
		in_construction_site_id,
		in_material_id,
		in_delta_quant,
		CASE WHEN in_pending_delta > 0 THEN NULL ELSE COALESCE(in_delta_amount, 0) END,
		GREATEST(in_pending_delta, 0)
	)
	ON CONFLICT (construction_site_id, material_id)
	DO UPDATE
	SET
		quant = rg_materials_current.quant + EXCLUDED.quant,
		pending_count = rg_materials_current.pending_count + in_pending_delta,
		amount = CASE
			WHEN rg_materials_current.pending_count + in_pending_delta > 0 THEN NULL
			ELSE COALESCE(rg_materials_current.amount, 0) + COALESCE(in_delta_amount, 0)
		END;

	DELETE FROM public.rg_materials_current
	WHERE construction_site_id = in_construction_site_id
		AND material_id = in_material_id
		AND quant = 0
		AND pending_count = 0
		AND COALESCE(amount, 0) = 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ra_materials_process()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM public.rg_materials_apply_delta(
			NEW.effective_at,
			NEW.construction_site_id,
			NEW.material_id,
			NEW.quant,
			NEW.amount,
			CASE WHEN NEW.amount_pending THEN 1 ELSE 0 END
		);
		RETURN NEW;
	END IF;

	IF TG_OP = 'DELETE' THEN
		PERFORM public.rg_materials_apply_delta(
			OLD.effective_at,
			OLD.construction_site_id,
			OLD.material_id,
			-OLD.quant,
			CASE WHEN OLD.amount IS NULL THEN NULL ELSE -OLD.amount END,
			CASE WHEN OLD.amount_pending THEN -1 ELSE 0 END
		);
		RETURN OLD;
	END IF;

	RETURN NEW;
END;
$function$;

DROP FUNCTION IF EXISTS public.ra_materials_add_act(timestamptz, text, bigint, integer, integer, numeric);

CREATE OR REPLACE FUNCTION public.ra_materials_add_act(
	in_effective_at timestamptz,
	in_recorder_type text,
	in_recorder_id bigint,
	in_recorder_item_id bigint,
	in_movement_order smallint,
	in_construction_site_id integer,
	in_material_id integer,
	in_quant numeric(19, 4),
	in_source_amount numeric(19, 4) DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
	v_id bigint;
BEGIN
	INSERT INTO public.ra_materials (
		effective_at,
		recorder_type,
		recorder_id,
		recorder_item_id,
		movement_order,
		construction_site_id,
		material_id,
		quant,
		source_amount,
		amount,
		amount_pending
	)
	VALUES (
		in_effective_at,
		in_recorder_type,
		in_recorder_id,
		in_recorder_item_id,
		in_movement_order,
		in_construction_site_id,
		in_material_id,
		in_quant,
		in_source_amount,
		CASE WHEN in_source_amount IS NULL THEN NULL ELSE in_source_amount END,
		in_source_amount IS NULL AND in_quant > 0
	)
	RETURNING id INTO v_id;

	RETURN v_id;
END;
$function$;

COMMENT ON FUNCTION public.ra_materials_add_act(timestamptz, text, bigint, bigint, smallint, integer, integer, numeric, numeric) IS
	'Adds one immutable quantity/source movement. Calculated monetary amount is assigned by materials_revalue().';

CREATE OR REPLACE FUNCTION public.rg_materials_rebuild()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
	TRUNCATE TABLE public.rg_materials_period, public.rg_materials_current;

	INSERT INTO public.rg_materials_period (
		period_start,
		construction_site_id,
		material_id,
		quant,
		amount,
		pending_count
	)
	SELECT
		public.register_month_start(action.effective_at),
		action.construction_site_id,
		action.material_id,
		SUM(action.quant)::numeric(19, 4),
		CASE
			WHEN bool_or(action.amount_pending OR action.amount IS NULL) THEN NULL
			ELSE SUM(action.amount)::numeric(19, 4)
		END,
		COUNT(*) FILTER (WHERE action.amount_pending OR action.amount IS NULL)::integer
	FROM public.ra_materials AS action
	GROUP BY
		public.register_month_start(action.effective_at),
		action.construction_site_id,
		action.material_id
	HAVING SUM(action.quant) <> 0
		OR COUNT(*) FILTER (WHERE action.amount_pending OR action.amount IS NULL) > 0
		OR COALESCE(SUM(action.amount), 0) <> 0;

	INSERT INTO public.rg_materials_current (
		construction_site_id,
		material_id,
		quant,
		amount,
		pending_count
	)
	SELECT
		action.construction_site_id,
		action.material_id,
		SUM(action.quant)::numeric(19, 4),
		CASE
			WHEN bool_or(action.amount_pending OR action.amount IS NULL) THEN NULL
			ELSE SUM(action.amount)::numeric(19, 4)
		END,
		COUNT(*) FILTER (WHERE action.amount_pending OR action.amount IS NULL)::integer
	FROM public.ra_materials AS action
	GROUP BY action.construction_site_id, action.material_id
	HAVING SUM(action.quant) <> 0
		OR COUNT(*) FILTER (WHERE action.amount_pending OR action.amount IS NULL) > 0
		OR COALESCE(SUM(action.amount), 0) <> 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.materials_revalue()
RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE
	v_allow_negative boolean;
	v_pass integer := 0;
	v_max_passes integer;
	v_changed integer;
	v_total_pending integer;
	v_row record;
	v_state_quant numeric;
	v_state_amount numeric;
	v_out_quant numeric;
	v_covered numeric;
	v_known_amount numeric;
	v_unit_cost numeric;
	v_in_amount numeric;
	v_remaining_quant numeric;
	v_remaining_amount numeric;
	v_cover_remaining numeric;
	v_alloc_quant numeric;
	v_alloc_amount numeric;
	v_pending record;
BEGIN
	PERFORM set_config('skstruktura.material_valuation_internal', 'on', true);

	SELECT materials_allow_negative_open_period
	INTO v_allow_negative
	FROM public.register_settings
	WHERE id = 1;

	CREATE TEMP TABLE IF NOT EXISTS pg_temp.material_valuation_prev (
		action_id bigint PRIMARY KEY,
		amount numeric(19, 4),
		amount_pending boolean NOT NULL
	) ON COMMIT DROP;
	TRUNCATE pg_temp.material_valuation_prev;

	INSERT INTO pg_temp.material_valuation_prev(action_id, amount, amount_pending)
	SELECT id, amount, amount_pending
	FROM public.ra_materials;

	SELECT GREATEST(COUNT(*) + 1, 2)::integer
	INTO v_max_passes
	FROM public.ra_materials
	WHERE recorder_type = 'MaterialTransfer';

	LOOP
		v_pass := v_pass + 1;

		CREATE TEMP TABLE IF NOT EXISTS pg_temp.material_valuation_state (
			construction_site_id integer NOT NULL,
			material_id integer NOT NULL,
			quant numeric NOT NULL,
			amount numeric,
			PRIMARY KEY (construction_site_id, material_id)
		) ON COMMIT DROP;
		TRUNCATE pg_temp.material_valuation_state;

		CREATE TEMP TABLE IF NOT EXISTS pg_temp.material_valuation_work (
			action_id bigint PRIMARY KEY,
			known_amount numeric NOT NULL DEFAULT 0,
			pending_quant numeric NOT NULL DEFAULT 0,
			is_pending boolean NOT NULL DEFAULT false
		) ON COMMIT DROP;
		TRUNCATE pg_temp.material_valuation_work;

		FOR v_row IN
			SELECT
				action.*,
				CASE
					WHEN action.recorder_type = 'MaterialTransfer' AND action.movement_order = 2 THEN (
						SELECT abs(prev.amount)
						FROM public.ra_materials AS source_action
						LEFT JOIN pg_temp.material_valuation_prev AS prev
							ON prev.action_id = source_action.id
						WHERE source_action.recorder_type = action.recorder_type
							AND source_action.recorder_id = action.recorder_id
							AND source_action.recorder_item_id = action.recorder_item_id
							AND source_action.movement_order = 1
						LIMIT 1
					)
					ELSE action.source_amount
				END AS incoming_amount
			FROM public.ra_materials AS action
			ORDER BY
				action.effective_at,
				CASE action.recorder_type
					WHEN 'MaterialReceipt' THEN 1
					WHEN 'MaterialTransfer' THEN 2
					WHEN 'MaterialConsumption' THEN 3
					ELSE 9
				END,
				action.recorder_id,
				action.recorder_item_id NULLS LAST,
				action.movement_order,
				action.id
		LOOP
			INSERT INTO pg_temp.material_valuation_state(
				construction_site_id,
				material_id,
				quant,
				amount
			)
			VALUES (v_row.construction_site_id, v_row.material_id, 0, 0)
			ON CONFLICT DO NOTHING;

			SELECT quant, amount
			INTO v_state_quant, v_state_amount
			FROM pg_temp.material_valuation_state
			WHERE construction_site_id = v_row.construction_site_id
				AND material_id = v_row.material_id;

			IF v_row.quant > 0 THEN
				v_in_amount := v_row.incoming_amount;

				IF v_in_amount IS NULL THEN
					UPDATE pg_temp.material_valuation_state
					SET quant = quant + v_row.quant,
						amount = NULL
					WHERE construction_site_id = v_row.construction_site_id
						AND material_id = v_row.material_id;

					INSERT INTO pg_temp.material_valuation_work(action_id, is_pending)
					VALUES (v_row.id, true)
					ON CONFLICT (action_id) DO UPDATE SET is_pending = true;
					CONTINUE;
				END IF;

				v_remaining_quant := v_row.quant;
				v_remaining_amount := v_in_amount;
				v_unit_cost := CASE WHEN v_row.quant = 0 THEN 0 ELSE v_in_amount / v_row.quant END;

				IF v_state_quant < 0 THEN
					v_cover_remaining := LEAST(v_remaining_quant, -v_state_quant);
					FOR v_pending IN
						SELECT work.action_id, work.pending_quant, work.known_amount
						FROM pg_temp.material_valuation_work AS work
						JOIN public.ra_materials AS pending_action ON pending_action.id = work.action_id
						WHERE work.pending_quant > 0
							AND pending_action.construction_site_id = v_row.construction_site_id
							AND pending_action.material_id = v_row.material_id
						ORDER BY
							pending_action.effective_at,
							pending_action.id
					LOOP
						EXIT WHEN v_cover_remaining <= 0;
						v_alloc_quant := LEAST(v_cover_remaining, v_pending.pending_quant);
						v_alloc_amount := CASE
							WHEN v_alloc_quant = v_remaining_quant THEN v_remaining_amount
							ELSE round(v_alloc_quant * v_unit_cost, 4)
						END;

						UPDATE pg_temp.material_valuation_work
						SET
							known_amount = known_amount + v_alloc_amount,
							pending_quant = pending_quant - v_alloc_quant,
							is_pending = (pending_quant - v_alloc_quant) > 0
						WHERE action_id = v_pending.action_id;

						v_remaining_quant := v_remaining_quant - v_alloc_quant;
						v_remaining_amount := v_remaining_amount - v_alloc_amount;
						v_cover_remaining := v_cover_remaining - v_alloc_quant;
					END LOOP;
				END IF;

				UPDATE pg_temp.material_valuation_state
				SET
					quant = quant + v_row.quant,
					amount = CASE
						WHEN quant + v_row.quant < 0 THEN NULL
						WHEN amount IS NULL AND quant >= 0 THEN NULL
						WHEN quant < 0 THEN GREATEST(v_remaining_amount, 0)
						ELSE COALESCE(amount, 0) + v_in_amount
					END
				WHERE construction_site_id = v_row.construction_site_id
					AND material_id = v_row.material_id;

				INSERT INTO pg_temp.material_valuation_work(action_id, known_amount, pending_quant, is_pending)
				VALUES (v_row.id, v_in_amount, 0, false)
				ON CONFLICT (action_id) DO UPDATE
				SET known_amount = EXCLUDED.known_amount, pending_quant = 0, is_pending = false;
			ELSE
				v_out_quant := -v_row.quant;
				v_known_amount := 0;

				IF v_state_quant > 0 AND v_state_amount IS NOT NULL THEN
					v_covered := LEAST(v_out_quant, v_state_quant);
					IF v_covered = v_state_quant THEN
						v_known_amount := v_state_amount;
					ELSE
						v_known_amount := round((v_state_amount / v_state_quant) * v_covered, 4);
					END IF;
				ELSE
					v_covered := 0;
				END IF;

				INSERT INTO pg_temp.material_valuation_work(
					action_id,
					known_amount,
					pending_quant,
					is_pending
				)
				VALUES (
					v_row.id,
					v_known_amount,
					v_out_quant - v_covered,
					(v_out_quant - v_covered) > 0
				)
				ON CONFLICT (action_id) DO UPDATE
				SET
					known_amount = EXCLUDED.known_amount,
					pending_quant = EXCLUDED.pending_quant,
					is_pending = EXCLUDED.is_pending;

				UPDATE pg_temp.material_valuation_state
				SET
					quant = quant - v_out_quant,
					amount = CASE
						WHEN v_out_quant > v_covered THEN NULL
						WHEN quant - v_out_quant = 0 THEN 0
						WHEN amount IS NULL THEN NULL
						ELSE amount - v_known_amount
					END
				WHERE construction_site_id = v_row.construction_site_id
					AND material_id = v_row.material_id;

				IF NOT v_allow_negative AND v_state_quant - v_out_quant < 0 THEN
					RAISE EXCEPTION 'Negative material inventory is disabled: site %, material %, action % would produce quantity %',
						v_row.construction_site_id,
						v_row.material_id,
						v_row.id,
						v_state_quant - v_out_quant
						USING ERRCODE = '23514';
				END IF;
			END IF;
		END LOOP;

		UPDATE public.ra_materials AS action
		SET
			amount = CASE
				WHEN action.quant > 0 THEN work.known_amount::numeric(19, 4)
				WHEN work.is_pending THEN NULL
				ELSE (-work.known_amount)::numeric(19, 4)
			END,
			amount_pending = work.is_pending
		FROM pg_temp.material_valuation_work AS work
		WHERE work.action_id = action.id;

		SELECT COUNT(*)::integer
		INTO v_changed
		FROM public.ra_materials AS action
		LEFT JOIN pg_temp.material_valuation_prev AS prev ON prev.action_id = action.id
		WHERE prev.action_id IS NULL
			OR action.amount IS DISTINCT FROM prev.amount
			OR action.amount_pending IS DISTINCT FROM prev.amount_pending;

		TRUNCATE pg_temp.material_valuation_prev;
		INSERT INTO pg_temp.material_valuation_prev(action_id, amount, amount_pending)
		SELECT id, amount, amount_pending
		FROM public.ra_materials;

		EXIT WHEN v_changed = 0 OR v_pass >= v_max_passes;
	END LOOP;

	PERFORM public.rg_materials_rebuild();

	SELECT COUNT(*)::integer
	INTO v_total_pending
	FROM public.ra_materials
	WHERE amount_pending OR amount IS NULL;

	RETURN v_total_pending;
END;
$function$;

COMMENT ON FUNCTION public.materials_revalue() IS
	'Deterministically recalculates weighted-average monetary values for all material movements. Negative open-period shortages remain pending until later valued receipts resolve them; transfer values propagate over repeated passes.';

DROP FUNCTION IF EXISTS public.rg_materials_balance(integer[], integer[]);
CREATE OR REPLACE FUNCTION public.rg_materials_balance(
	in_construction_site_ids integer[] DEFAULT NULL,
	in_material_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	construction_site_id integer,
	material_id integer,
	quant numeric(19, 4),
	amount numeric(19, 4),
	average_cost numeric(19, 6),
	amount_pending boolean
)
LANGUAGE sql
STABLE
AS $function$
	SELECT
		balance.construction_site_id,
		balance.material_id,
		balance.quant,
		balance.amount,
		CASE
			WHEN balance.amount IS NULL OR balance.quant = 0 THEN NULL
			ELSE (balance.amount / balance.quant)::numeric(19, 6)
		END,
		balance.pending_count > 0
	FROM public.rg_materials_current AS balance
	WHERE (
		in_construction_site_ids IS NULL
		OR cardinality(in_construction_site_ids) = 0
		OR balance.construction_site_id = ANY(in_construction_site_ids)
	)
	AND (
		in_material_ids IS NULL
		OR cardinality(in_material_ids) = 0
		OR balance.material_id = ANY(in_material_ids)
	)
	AND (balance.quant <> 0 OR balance.pending_count > 0 OR COALESCE(balance.amount, 0) <> 0)
	ORDER BY balance.construction_site_id, balance.material_id;
$function$;

DROP FUNCTION IF EXISTS public.rg_materials_balance(timestamptz, integer[], integer[]);
CREATE OR REPLACE FUNCTION public.rg_materials_balance(
	in_effective_at timestamptz,
	in_construction_site_ids integer[] DEFAULT NULL,
	in_material_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	construction_site_id integer,
	material_id integer,
	quant numeric(19, 4),
	amount numeric(19, 4),
	average_cost numeric(19, 6),
	amount_pending boolean
)
LANGUAGE sql
STABLE
AS $function$
	WITH movements AS (
		SELECT action.*
		FROM public.ra_materials AS action
		WHERE action.effective_at <= in_effective_at
			AND (
				in_construction_site_ids IS NULL
				OR cardinality(in_construction_site_ids) = 0
				OR action.construction_site_id = ANY(in_construction_site_ids)
			)
			AND (
				in_material_ids IS NULL
				OR cardinality(in_material_ids) = 0
				OR action.material_id = ANY(in_material_ids)
			)
	), grouped AS (
		SELECT
			construction_site_id,
			material_id,
			SUM(quant)::numeric(19, 4) AS quant,
			CASE
				WHEN bool_or(amount_pending OR amount IS NULL) THEN NULL
				ELSE SUM(amount)::numeric(19, 4)
			END AS amount,
			bool_or(amount_pending OR amount IS NULL) AS amount_pending
		FROM movements
		GROUP BY construction_site_id, material_id
	)
	SELECT
		grouped.construction_site_id,
		grouped.material_id,
		grouped.quant,
		grouped.amount,
		CASE
			WHEN grouped.amount IS NULL OR grouped.quant = 0 THEN NULL
			ELSE (grouped.amount / grouped.quant)::numeric(19, 6)
		END,
		grouped.amount_pending
	FROM grouped
	WHERE grouped.quant <> 0 OR grouped.amount_pending OR COALESCE(grouped.amount, 0) <> 0
	ORDER BY grouped.construction_site_id, grouped.material_id;
$function$;

CREATE OR REPLACE FUNCTION public.materials_close_period(
	in_closed_through date,
	in_user_id integer DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
	v_current_closed date;
	v_cutoff timestamptz;
	v_pending integer;
	v_negative integer;
	v_closure_id bigint;
BEGIN
	IF in_closed_through IS NULL THEN
		RAISE EXCEPTION 'closed_through is required' USING ERRCODE = '22004';
	END IF;

	SELECT materials_closed_through
	INTO v_current_closed
	FROM public.register_settings
	WHERE id = 1
	FOR UPDATE;

	IF v_current_closed IS NOT NULL AND in_closed_through <= v_current_closed THEN
		RAISE EXCEPTION 'New closing date % must be later than current closing date %', in_closed_through, v_current_closed
			USING ERRCODE = '22023';
	END IF;

	PERFORM public.materials_revalue();

	v_cutoff := ((in_closed_through + 1)::timestamp AT TIME ZONE public.register_business_timezone()) - interval '1 microsecond';

	SELECT COUNT(*)::integer
	INTO v_pending
	FROM public.ra_materials
	WHERE effective_at <= v_cutoff
		AND (amount_pending OR amount IS NULL);

	IF v_pending > 0 THEN
		RAISE EXCEPTION 'Cannot close material accounting through %: % movement(s) still have pending monetary valuation', in_closed_through, v_pending
			USING ERRCODE = '23514';
	END IF;

	WITH ordered AS (
		SELECT
			action.construction_site_id,
			action.material_id,
			action.id,
			SUM(action.quant) OVER (
				PARTITION BY action.construction_site_id, action.material_id
				ORDER BY
					action.effective_at,
					CASE action.recorder_type
						WHEN 'MaterialReceipt' THEN 1
						WHEN 'MaterialTransfer' THEN 2
						WHEN 'MaterialConsumption' THEN 3
						ELSE 9
					END,
					action.recorder_id,
					action.recorder_item_id NULLS LAST,
					action.movement_order,
					action.id
				ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
			) AS running_quant
		FROM public.ra_materials AS action
		WHERE action.effective_at <= v_cutoff
	)
	SELECT COUNT(*)::integer
	INTO v_negative
	FROM ordered
	WHERE running_quant < 0;

	IF v_negative > 0 THEN
		RAISE EXCEPTION 'Cannot close material accounting through %: % material balance(s) are negative', in_closed_through, v_negative
			USING ERRCODE = '23514';
	END IF;

	INSERT INTO public.material_valuation_closures(closed_through, closed_by)
	VALUES (in_closed_through, in_user_id)
	RETURNING id INTO v_closure_id;

	INSERT INTO public.material_valuation_snapshots(
		closure_id,
		construction_site_id,
		material_id,
		quant,
		amount
	)
	SELECT
		v_closure_id,
		balance.construction_site_id,
		balance.material_id,
		balance.quant,
		COALESCE(balance.amount, 0)
	FROM public.rg_materials_balance(v_cutoff, NULL, NULL) AS balance
	WHERE balance.quant <> 0 OR COALESCE(balance.amount, 0) <> 0;

	UPDATE public.register_settings
	SET materials_closed_through = in_closed_through
	WHERE id = 1;

	RETURN v_closure_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.materials_reopen_period(in_user_id integer DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
	v_closure_id bigint;
BEGIN
	SELECT id
	INTO v_closure_id
	FROM public.material_valuation_closures
	WHERE reopened_at IS NULL
	ORDER BY id DESC
	LIMIT 1
	FOR UPDATE;

	IF v_closure_id IS NULL THEN
		UPDATE public.register_settings
		SET materials_closed_through = NULL
		WHERE id = 1;
		RETURN NULL;
	END IF;

	UPDATE public.material_valuation_closures
	SET
		reopened_at = CURRENT_TIMESTAMP,
		reopened_by = in_user_id
	WHERE id = v_closure_id;

	UPDATE public.register_settings
	SET materials_closed_through = NULL
	WHERE id = 1;

	RETURN v_closure_id;
END;
$function$;

DROP VIEW IF EXISTS public.material_balances_list;
CREATE VIEW public.material_balances_list AS
SELECT
	material.id,
	balance.construction_site_id,
	public.construction_sites_ref(site) AS construction_site,
	material.material_type_id,
	public.material_types_ref(material_type) AS material_type,
	material_type.name AS material_type_name,
	balance.material_id,
	public.materials_ref(material) AS material,
	material.name AS material_name,
	material.measure_unit_id,
	public.measure_units_ref(measure_unit) AS measure_unit,
	balance.quant::numeric(19, 4) AS balance,
	balance.amount::numeric(19, 4) AS amount,
	CASE
		WHEN balance.amount IS NULL OR balance.quant = 0 THEN NULL
		ELSE (balance.amount / balance.quant)::numeric(19, 6)
	END AS average_cost,
	balance.pending_count > 0 AS amount_pending
FROM public.rg_materials_current AS balance
JOIN public.construction_sites AS site
	ON site.id = balance.construction_site_id
JOIN public.materials AS material
	ON material.id = balance.material_id
JOIN public.material_types AS material_type
	ON material_type.id = material.material_type_id
JOIN public.measure_units AS measure_unit
	ON measure_unit.id = material.measure_unit_id
WHERE balance.quant <> 0 OR balance.pending_count > 0 OR COALESCE(balance.amount, 0) <> 0;


-- Rebuild the authoritative action ledger from source documents so every
-- pre-existing movement receives recorder-line identity and receipt cost basis.
TRUNCATE TABLE public.ra_materials RESTART IDENTITY;

SELECT public.ra_materials_add_act(
	receipt.date,
	'MaterialReceipt',
	receipt.id,
	item.id,
	1::smallint,
	COALESCE(item.construction_site_id, receipt.construction_site_id),
	item.material_id,
	item.quant,
	CASE
		WHEN settings.materials_exclude_vat_from_cost THEN item.amount - item.vat_amount
		ELSE item.amount
	END
)
FROM public.material_receipts AS receipt
JOIN public.material_receipt_items AS item
	ON item.material_receipt_id = receipt.id
CROSS JOIN public.register_settings AS settings
WHERE settings.id = 1
ORDER BY receipt.date, receipt.id, item.line_num, item.id;

SELECT public.ra_materials_add_act(
	consumption.date,
	'MaterialConsumption',
	consumption.id,
	item.id,
	1::smallint,
	consumption.construction_site_id,
	item.material_id,
	-item.quant,
	NULL
)
FROM public.material_consumptions AS consumption
JOIN public.material_consumption_items AS item
	ON item.material_consumption_id = consumption.id
ORDER BY consumption.date, consumption.id, item.line_num, item.id;

SELECT public.ra_materials_add_act(
	transfer.date,
	'MaterialTransfer',
	transfer.id,
	movement.id,
	movement.movement_order::smallint,
	movement.construction_site_id,
	movement.material_id,
	movement.quant,
	NULL
)
FROM public.material_transfers AS transfer
JOIN LATERAL (
	SELECT
		item.line_num,
		item.id,
		transfer.source_construction_site_id AS construction_site_id,
		item.material_id,
		-item.quant AS quant,
		1 AS movement_order
	FROM public.material_transfer_items AS item
	WHERE item.material_transfer_id = transfer.id

	UNION ALL

	SELECT
		item.line_num,
		item.id,
		transfer.destination_construction_site_id AS construction_site_id,
		item.material_id,
		item.quant AS quant,
		2 AS movement_order
	FROM public.material_transfer_items AS item
	WHERE item.material_transfer_id = transfer.id
) AS movement ON true
ORDER BY transfer.date, transfer.id, movement.line_num, movement.id, movement.movement_order;

SELECT public.materials_revalue();

INSERT INTO public.permissions (code, description)
VALUES
	('inventoryValuation.view', 'Просмотр денежной оценки материалов'),
	('inventoryValuation.manage', 'Закрытие, открытие и пересчёт денежной оценки материалов')
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO public.role_permissions(role_id, permission_code)
VALUES ('accountant'::public.role_types, 'materialBalance.list')
ON CONFLICT DO NOTHING;

WITH roles(role_id, permission_code) AS (
	VALUES
		('admin'::public.role_types, 'inventoryValuation.view'),
		('admin'::public.role_types, 'inventoryValuation.manage'),
		('accountant'::public.role_types, 'inventoryValuation.view'),
		('accountant'::public.role_types, 'inventoryValuation.manage'),
		('construction_site_manager'::public.role_types, 'inventoryValuation.view')
)
INSERT INTO public.role_permissions(role_id, permission_code)
SELECT role_id, permission_code
FROM roles
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes(
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'inventoryValuation',
	'/inventory-valuation',
	'Оценка материалов',
	'Материалы',
	'pi pi-wallet',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.section,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types),
		('accountant'::public.role_types),
		('construction_site_manager'::public.role_types)
)
INSERT INTO public.main_menus(role_id, caption, icon, sort_order, is_active)
SELECT roles.role_id, 'Материалы', NULL, 40, true
FROM roles
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = roles.role_id
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Материалы'
);

INSERT INTO public.main_menus(role_id, parent_id, caption, route_id, icon, sort_order, is_active)
SELECT
	'accountant'::public.role_types,
	parent.id,
	'Остатки материалов',
	route.id,
	NULL,
	50,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT menu.id
	FROM public.main_menus AS menu
	WHERE menu.role_id = 'accountant'::public.role_types
		AND menu.user_id IS NULL
		AND menu.parent_id IS NULL
		AND menu.caption = 'Материалы'
	ORDER BY menu.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'materialBalance'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'accountant'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types),
		('accountant'::public.role_types),
		('construction_site_manager'::public.role_types)
)
INSERT INTO public.main_menus(role_id, parent_id, caption, route_id, icon, sort_order, is_active)
SELECT
	roles.role_id,
	parent.id,
	'Оценка материалов',
	route.id,
	NULL,
	60,
	true
FROM roles
JOIN public.application_routes AS route ON route.name = 'inventoryValuation'
JOIN LATERAL (
	SELECT menu.id
	FROM public.main_menus AS menu
	WHERE menu.role_id = roles.role_id
		AND menu.user_id IS NULL
		AND menu.parent_id IS NULL
		AND menu.caption = 'Материалы'
	ORDER BY menu.id
	LIMIT 1
) AS parent ON true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = roles.role_id
		AND existing.user_id IS NULL
		AND existing.route_id = route.id
);

COMMIT;
