-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'materialConsumptionItem.create',
	'materialConsumptionItem.list',
	'materialConsumptionItem.detail',
	'materialConsumptionItem.update',
	'materialConsumptionItem.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'materialConsumptionItem.create',
	'materialConsumptionItem.list',
	'materialConsumptionItem.detail',
	'materialConsumptionItem.update',
	'materialConsumptionItem.delete'
);

DROP TABLE IF EXISTS public.material_consumption_items;

COMMIT;
