-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.material_receipt_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	material_receipt_id integer NOT NULL REFERENCES public.material_receipts(id) ON DELETE CASCADE ON UPDATE CASCADE,
	material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quant numeric(19, 4) NOT NULL,
	price numeric(15, 2) NOT NULL,
	amount numeric(15, 2) NOT NULL,
	CHECK (line_num > 0),
	CHECK (quant > 0),
	CHECK (price >= 0),
	CHECK (amount >= 0)
);

COMMENT ON TABLE public.material_receipt_items IS 'Material receipt document lines.';
COMMENT ON COLUMN public.material_receipt_items.line_num IS 'Line number within the document.';
COMMENT ON COLUMN public.material_receipt_items.material_receipt_id IS 'Parent material receipt document.';
COMMENT ON COLUMN public.material_receipt_items.material_id IS 'Material.';
COMMENT ON COLUMN public.material_receipt_items.measure_unit_id IS 'Measurement unit.';
COMMENT ON COLUMN public.material_receipt_items.quant IS 'Material quantity.';
COMMENT ON COLUMN public.material_receipt_items.price IS 'Unit price.';
COMMENT ON COLUMN public.material_receipt_items.amount IS 'Line amount.';

CREATE UNIQUE INDEX material_receipt_items_material_receipt_id_line_num_idx
	ON public.material_receipt_items USING btree (material_receipt_id, line_num);

WITH required(code, description) AS (
	VALUES
		('materialReceiptItem.create', 'Создание строки поступления материалов'),
		('materialReceiptItem.list', 'Просмотр строк поступления материалов'),
		('materialReceiptItem.detail', 'Просмотр строки поступления материалов'),
		('materialReceiptItem.update', 'Изменение строки поступления материалов'),
		('materialReceiptItem.delete', 'Удаление строки поступления материалов')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialReceiptItem.create'),
		('materialReceiptItem.list'),
		('materialReceiptItem.detail'),
		('materialReceiptItem.update'),
		('materialReceiptItem.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

COMMIT;
