-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TYPE public.material_status_types AS ENUM (
    'at_work',
    'on_maintenance'
);

CREATE TABLE public.material_statuses (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	created_at timestamp with time zone NOT NULL DEFAULT now(),
	material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE CASCADE ON UPDATE CASCADE,
	status public.material_status_types NOT NULL,
	is_active boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.material_statuses IS 'Material status reference data.';
COMMENT ON COLUMN public.material_statuses.created_at IS 'Document date and time';
COMMENT ON COLUMN public.material_statuses.material_id IS 'Material reference';
COMMENT ON COLUMN public.material_statuses.status IS 'Material status';

CREATE INDEX material_statuses_material_id_idx
	ON public.material_statuses USING btree (material_id);

WITH required(code, description) AS (
	VALUES
		('materialStatus.create', 'Создание статуса материала'),
		('materialStatus.list', 'Просмотр списка статусов материалов'),
		('materialStatus.detail', 'Просмотр статуса материала'),
		('materialStatus.update', 'Изменение статуса материала'),
		('materialStatus.delete', 'Удаление статуса материала')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialStatus.create'),
		('materialStatus.list'),
		('materialStatus.detail'),
		('materialStatus.update'),
		('materialStatus.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'materialStatuses',
	'/material-statuses',
	'Статусы материалов',
	'Справочники',
	'pi pi-tags',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Статусы материалов',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Статусы материалов'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Статусы материалов';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Статусы материалов'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Статусы материалов',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'materialStatuses'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Статусы материалов'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Статусы материалов',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Статусы материалов'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'materialStatuses'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);


CREATE OR REPLACE VIEW public.material_statuses_list AS
SELECT
	row.id,
	row.created_at,
	row.material_id,
	public.materials_ref(mat) AS material,
	row.status,
	row.is_active
FROM public.material_statuses AS row
LEFT JOIN public.materials AS mat ON mat.id = row.material_id
;

COMMIT;
