BEGIN;

ALTER TABLE public.measure_units
	ADD COLUMN IF NOT EXISTS okei_code varchar(4);

CREATE UNIQUE INDEX IF NOT EXISTS measure_units_okei_code_idx
	ON public.measure_units (okei_code)
	WHERE okei_code IS NOT NULL;

COMMENT ON COLUMN public.measure_units.okei_code IS
	'Russian OKEI unit code used for electronic document matching.';

ALTER TABLE integration_diadoc.state
	ADD COLUMN enabled boolean NOT NULL DEFAULT true,
	ADD COLUMN event_timestamp_from timestamptz,
	ADD COLUMN last_sync_started_at timestamptz,
	ADD COLUMN last_sync_finished_at timestamptz,
	ADD COLUMN last_sync_error text,
	ADD COLUMN cursor_reset_at timestamptz,
	ADD COLUMN cursor_reset_by text,
	ADD COLUMN version bigint NOT NULL DEFAULT 1;

UPDATE integration_diadoc.state
SET event_timestamp_from = CASE
	WHEN event_timestamp_from_ticks > 621355968000000000 THEN
		to_timestamp((event_timestamp_from_ticks - 621355968000000000)::numeric / 10000000)
	ELSE now()
END
WHERE event_timestamp_from IS NULL;

ALTER TABLE integration_diadoc.state
	ALTER COLUMN event_timestamp_from SET NOT NULL,
	ADD CONSTRAINT integration_diadoc_state_version_chk CHECK (version > 0);

CREATE TABLE integration_diadoc.documents (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	box_id text NOT NULL,
	message_id text NOT NULL,
	entity_id text NOT NULL,
	parent_entity_id text,
	event_id text,
	event_index_key text,
	event_timestamp timestamptz,
	status text NOT NULL DEFAULT 'received',
	attachment_type text NOT NULL,
	type_named_id text,
	document_function text,
	document_version text,
	document_number text,
	document_date date,
	file_name text,
	sender_box_id text,
	sender_name text,
	sender_inn text,
	sender_kpp text,
	supplier_id integer REFERENCES public.suppliers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	construction_site_id integer REFERENCES public.construction_sites(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	raw_content bytea,
	content_sha256 bytea,
	parsed_payload jsonb,
	line_count integer NOT NULL DEFAULT 0,
	amount_without_vat numeric(15, 2) NOT NULL DEFAULT 0,
	vat_amount numeric(15, 2) NOT NULL DEFAULT 0,
	amount_with_vat numeric(15, 2) NOT NULL DEFAULT 0,
	material_receipt_id integer UNIQUE REFERENCES public.material_receipts(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	last_error text,
	ignored_reason text,
	ignored_at timestamptz,
	ignored_by text,
	imported_at timestamptz,
	imported_by text,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	version bigint NOT NULL DEFAULT 1,
	CONSTRAINT integration_diadoc_documents_identity_key UNIQUE (box_id, message_id, entity_id),
	CONSTRAINT integration_diadoc_documents_status_chk CHECK (status IN (
		'received',
		'needs_matching',
		'ready',
		'imported',
		'ignored',
		'failed',
		'revoked',
		'superseded'
	)),
	CONSTRAINT integration_diadoc_documents_line_count_chk CHECK (line_count >= 0),
	CONSTRAINT integration_diadoc_documents_amounts_chk CHECK (
		amount_without_vat >= 0
		AND vat_amount >= 0
		AND amount_with_vat >= 0
	),
	CONSTRAINT integration_diadoc_documents_version_chk CHECK (version > 0)
);

CREATE INDEX integration_diadoc_documents_buffer_idx
	ON integration_diadoc.documents (status, document_date DESC, id DESC);

CREATE INDEX integration_diadoc_documents_supplier_idx
	ON integration_diadoc.documents (supplier_id, document_date DESC);

CREATE INDEX integration_diadoc_documents_sender_idx
	ON integration_diadoc.documents (sender_inn, sender_kpp);

COMMENT ON TABLE integration_diadoc.documents IS
	'Durable Diadoc UTD staging buffer. Ignored and imported rows are retained for replay idempotency.';
COMMENT ON COLUMN integration_diadoc.documents.raw_content IS
	'Exact source XML. This column must never be copied into the generic audit log.';
COMMENT ON COLUMN integration_diadoc.documents.amount_with_vat IS
	'Source document gross total including VAT.';

CREATE TABLE integration_diadoc.document_items (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	document_id bigint NOT NULL REFERENCES integration_diadoc.documents(id) ON DELETE CASCADE,
	line_num integer NOT NULL,
	source_product_code text,
	source_article text,
	source_gtin text,
	source_name text NOT NULL,
	source_okei_code varchar(4),
	source_unit_name text,
	source_quant numeric(19, 4) NOT NULL,
	source_price numeric(15, 6) NOT NULL DEFAULT 0,
	source_amount_without_vat numeric(15, 2) NOT NULL DEFAULT 0,
	source_vat_percent numeric(5, 2) NOT NULL DEFAULT 0,
	source_vat_amount numeric(15, 2) NOT NULL DEFAULT 0,
	source_amount_with_vat numeric(15, 2) NOT NULL DEFAULT 0,
	material_id integer REFERENCES public.materials(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	measure_unit_id integer REFERENCES public.measure_units(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	conversion_factor numeric(19, 8),
	import_quant numeric(19, 4),
	import_price numeric(15, 2),
	import_amount numeric(15, 2),
	import_vat_percent numeric(5, 2),
	import_vat_amount numeric(15, 2),
	mapping_source text,
	last_error text,
	CONSTRAINT integration_diadoc_document_items_line_key UNIQUE (document_id, line_num),
	CONSTRAINT integration_diadoc_document_items_line_num_chk CHECK (line_num > 0),
	CONSTRAINT integration_diadoc_document_items_quant_chk CHECK (source_quant > 0),
	CONSTRAINT integration_diadoc_document_items_values_chk CHECK (
		source_price >= 0
		AND source_amount_without_vat >= 0
		AND source_vat_percent >= 0
		AND source_vat_percent <= 100
		AND source_vat_amount >= 0
		AND source_vat_amount <= source_amount_with_vat
		AND source_amount_with_vat >= 0
	),
	CONSTRAINT integration_diadoc_document_items_conversion_chk CHECK (
		conversion_factor IS NULL OR conversion_factor > 0
	)
);

CREATE INDEX integration_diadoc_document_items_material_idx
	ON integration_diadoc.document_items (material_id);

COMMENT ON TABLE integration_diadoc.document_items IS
	'Parsed source UTD lines together with user-approved import targets and calculated receipt values.';

CREATE TABLE integration_diadoc.supplier_matches (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	box_id text NOT NULL,
	counteragent_box_id text NOT NULL,
	source_inn text,
	source_kpp text,
	supplier_id integer NOT NULL REFERENCES public.suppliers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT integration_diadoc_supplier_matches_key UNIQUE (box_id, counteragent_box_id)
);

CREATE TABLE integration_diadoc.supplier_material_matches (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	supplier_id integer NOT NULL REFERENCES public.suppliers(id) ON UPDATE CASCADE ON DELETE CASCADE,
	source_key_kind text NOT NULL,
	source_key text NOT NULL,
	source_name text,
	source_okei_code varchar(4) NOT NULL DEFAULT '',
	material_id integer NOT NULL REFERENCES public.materials(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	conversion_factor numeric(19, 8) NOT NULL DEFAULT 1,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT integration_diadoc_supplier_material_matches_kind_chk CHECK (
		source_key_kind IN ('product_code', 'article', 'gtin', 'name')
	),
	CONSTRAINT integration_diadoc_supplier_material_matches_factor_chk CHECK (conversion_factor > 0)
);

ALTER TABLE integration_diadoc.supplier_material_matches
	ADD CONSTRAINT integration_diadoc_supplier_material_matches_key UNIQUE (
		supplier_id,
		source_key_kind,
		source_key,
		source_okei_code
	);

ALTER TABLE public.audit_log
	ADD COLUMN schema_name text NOT NULL DEFAULT 'public';

DROP INDEX IF EXISTS public.audit_log_object_history_idx;
CREATE INDEX audit_log_object_history_idx
	ON public.audit_log (schema_name, table_name, record_id, changed_at DESC, id DESC);

CREATE OR REPLACE FUNCTION integration_diadoc.audit_selected_columns()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
	changes jsonb := '[]'::jsonb;
	column_name text;
	old_value jsonb;
	new_value jsonb;
	actor text;
	record_id text;
BEGIN
	actor := NULLIF(current_setting('app.user_name', true), '');
	actor := COALESCE(actor, current_user);
	IF TG_OP = 'DELETE' THEN
		record_id := COALESCE(to_jsonb(OLD)->>'id', '');
	ELSE
		record_id := COALESCE(to_jsonb(NEW)->>'id', '');
	END IF;

	FOREACH column_name IN ARRAY TG_ARGV
	LOOP
		old_value := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD)->column_name END;
		new_value := CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW)->column_name END;
		IF old_value IS DISTINCT FROM new_value THEN
			changes := changes || jsonb_build_object(
				'col', column_name,
				'alias', column_name,
				'old', old_value,
				'new', new_value
			);
		END IF;
	END LOOP;

	IF jsonb_array_length(changes) > 0 THEN
		INSERT INTO public.audit_log (
			schema_name,
			table_name,
			record_id,
			operation,
			changes,
			changed_at,
			changed_by
		)
		VALUES (
			TG_TABLE_SCHEMA,
			TG_TABLE_NAME,
			record_id,
			substring(TG_OP, 1, 1),
			changes,
			now(),
			actor
		);
	END IF;

	IF TG_OP = 'DELETE' THEN
		RETURN OLD;
	END IF;
	RETURN NEW;
END;
$function$;

CREATE TRIGGER integration_diadoc_documents_audit
	AFTER UPDATE ON integration_diadoc.documents
	FOR EACH ROW EXECUTE FUNCTION integration_diadoc.audit_selected_columns(
		'status',
		'supplier_id',
		'construction_site_id',
		'material_receipt_id',
		'ignored_reason',
		'ignored_at',
		'ignored_by',
		'imported_at',
		'imported_by',
		'last_error'
	);

CREATE TRIGGER integration_diadoc_document_items_audit
	AFTER UPDATE ON integration_diadoc.document_items
	FOR EACH ROW EXECUTE FUNCTION integration_diadoc.audit_selected_columns(
		'material_id',
		'measure_unit_id',
		'conversion_factor',
		'import_quant',
		'import_price',
		'import_amount',
		'import_vat_percent',
		'import_vat_amount',
		'mapping_source',
		'last_error'
	);

CREATE TRIGGER integration_diadoc_state_audit
	AFTER UPDATE ON integration_diadoc.state
	FOR EACH ROW EXECUTE FUNCTION integration_diadoc.audit_selected_columns(
		'enabled',
		'event_timestamp_from',
		'cursor_reset_at',
		'cursor_reset_by'
	);

CREATE TRIGGER integration_diadoc_supplier_matches_audit
	AFTER INSERT OR UPDATE OR DELETE ON integration_diadoc.supplier_matches
	FOR EACH ROW EXECUTE FUNCTION integration_diadoc.audit_selected_columns(
		'box_id',
		'counteragent_box_id',
		'source_inn',
		'source_kpp',
		'supplier_id'
	);

CREATE TRIGGER integration_diadoc_supplier_material_matches_audit
	AFTER INSERT OR UPDATE OR DELETE ON integration_diadoc.supplier_material_matches
	FOR EACH ROW EXECUTE FUNCTION integration_diadoc.audit_selected_columns(
		'supplier_id',
		'source_key_kind',
		'source_key',
		'source_name',
		'source_okei_code',
		'material_id',
		'conversion_factor'
	);

WITH required(code, description) AS (
	VALUES
		('diadocDocument.list', 'Просмотр буфера документов Диадока'),
		('diadocDocument.detail', 'Просмотр документа из буфера Диадока'),
		('diadocDocument.resolve', 'Сопоставление документа из Диадока'),
		('diadocDocument.ignore', 'Исключение документа из импорта Диадока'),
		('diadocDocument.import', 'Импорт документа из Диадока'),
		('diadocState.view', 'Просмотр состояния интеграции с Диадоком'),
		('diadocState.update', 'Изменение состояния интеграции с Диадоком'),
		('diadoc.sync', 'Запуск синхронизации с Диадоком')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES ('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('diadocDocument.list'),
		('diadocDocument.detail'),
		('diadocDocument.resolve'),
		('diadocDocument.ignore'),
		('diadocDocument.import'),
		('diadocState.view'),
		('diadocState.update'),
		('diadoc.sync')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.audit_column_aliases (
	table_name,
	column_name,
	column_alias,
	is_active
)
VALUES
	('material_receipt_items', 'vat_percent', 'Ставка НДС', true),
	('material_receipt_items', 'vat_amount', 'Сумма НДС', true),
	('measure_units', 'okei_code', 'Код ОКЕИ', true)
ON CONFLICT (table_name, column_name) DO UPDATE
SET
	column_alias = EXCLUDED.column_alias,
	is_active = true;

COMMIT;
