BEGIN;

CREATE TABLE public.max_in_messages (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	update_type text NOT NULL,
	max_user_id bigint,
	max_chat_id bigint,
	message jsonb NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT max_in_messages_update_type_not_empty CHECK (btrim(update_type) <> ''),
	CONSTRAINT max_in_messages_message_is_object CHECK (jsonb_typeof(message) = 'object')
);

COMMENT ON TABLE public.max_in_messages IS
	'Raw webhook updates received from MAX. The message column stores the complete Update JSON object.';
COMMENT ON COLUMN public.max_in_messages.update_type IS
	'Extracted MAX Update.update_type value for convenient filtering.';
COMMENT ON COLUMN public.max_in_messages.max_user_id IS
	'Extracted MAX platform user ID when it can be determined from the update.';
COMMENT ON COLUMN public.max_in_messages.max_chat_id IS
	'Extracted MAX chat ID when it can be determined from the update.';
COMMENT ON COLUMN public.max_in_messages.message IS
	'Complete raw MAX Update JSON object.';

CREATE INDEX max_in_messages_created_at_idx
	ON public.max_in_messages (created_at DESC, id DESC);
CREATE INDEX max_in_messages_update_type_idx
	ON public.max_in_messages (update_type, created_at DESC);
CREATE INDEX max_in_messages_max_user_id_idx
	ON public.max_in_messages (max_user_id, created_at DESC)
	WHERE max_user_id IS NOT NULL;
CREATE INDEX max_in_messages_max_chat_id_idx
	ON public.max_in_messages (max_chat_id, created_at DESC)
	WHERE max_chat_id IS NOT NULL;

CREATE TABLE public.max_out_messages (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	max_user_id bigint NOT NULL REFERENCES public.max_users(max_user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	message jsonb NOT NULL,
	metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
	status text NOT NULL DEFAULT 'pending',
	attempt_count integer NOT NULL DEFAULT 0,
	next_attempt_at timestamptz,
	locked_at timestamptz,
	sent_at timestamptz,
	created_at timestamptz NOT NULL DEFAULT now(),
	error_str text,
	CONSTRAINT max_out_messages_message_is_object CHECK (jsonb_typeof(message) = 'object'),
	CONSTRAINT max_out_messages_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object'),
	CONSTRAINT max_out_messages_status_check CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
	CONSTRAINT max_out_messages_attempt_count_check CHECK (attempt_count >= 0)
);

COMMENT ON TABLE public.max_out_messages IS
	'Durable outgoing MAX notification queue consumed by cmd/max.';
COMMENT ON COLUMN public.max_out_messages.max_user_id IS
	'MAX platform user ID and foreign key to max_users.max_user_id.';
COMMENT ON COLUMN public.max_out_messages.message IS
	'JSON request body compatible with MAX POST /messages NewMessageBody.';
COMMENT ON COLUMN public.max_out_messages.metadata IS
	'Optional application metadata such as source entity and notification type.';
COMMENT ON COLUMN public.max_out_messages.status IS
	'Queue state: pending, sending, sent, or failed.';
COMMENT ON COLUMN public.max_out_messages.locked_at IS
	'Time the sender claimed this message. Stale sending rows are automatically requeued.';

CREATE INDEX max_out_messages_ready_idx
	ON public.max_out_messages (next_attempt_at, created_at, id)
	WHERE status = 'pending';
CREATE INDEX max_out_messages_sending_idx
	ON public.max_out_messages (locked_at, id)
	WHERE status = 'sending';
CREATE INDEX max_out_messages_max_user_id_idx
	ON public.max_out_messages (max_user_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.max_out_messages_notify_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	PERFORM pg_notify('max_out_messages', NEW.id::text);
	RETURN NEW;
END;
$$;

CREATE TRIGGER max_out_messages_notify_insert
AFTER INSERT ON public.max_out_messages
FOR EACH ROW
EXECUTE FUNCTION public.max_out_messages_notify_insert();

INSERT INTO public.permissions (code, description)
VALUES ('maxNotification.send', 'Отправка уведомлений пользователям MAX')
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO public.role_permissions (role_id, permission_code)
VALUES ('admin'::public.role_types, 'maxNotification.send')
ON CONFLICT DO NOTHING;

COMMIT;

