-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.construction_sites (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name varchar(250) NOT NULL,
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> '')
);

COMMENT ON TABLE public.construction_sites IS 'Construction site reference data.';
COMMENT ON COLUMN public.construction_sites.name IS 'Display name of the construction site.';

CREATE INDEX construction_sites_name_idx
	ON public.construction_sites USING btree (lower(name));

WITH required(code, description) AS (
	VALUES
		('constructionSite.create', 'Создание объекта строительства'),
		('constructionSite.list', 'Просмотр списка объектов строительства'),
		('constructionSite.detail', 'Просмотр объекта строительства'),
		('constructionSite.update', 'Изменение объекта строительства'),
		('constructionSite.delete', 'Удаление объекта строительства')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
	('admin'::role_types)
), required(permission_code) AS (
	VALUES
		('constructionSite.create'),
		('constructionSite.list'),
		('constructionSite.detail'),
		('constructionSite.update'),
		('constructionSite.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'constructionSites',
	'/construction-sites',
	'Объекты строительства',
	'Справочники',
	'pi pi-car',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.section,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin',
	'Объекты',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Объекты'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Объекты';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Объекты'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Объекты строительства',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'vehicleBrands'
	AND existing.role_id = 'admin'
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Объекты'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin',
	parent.id,
	'Объекты строительства',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Объекты'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'vehicleBrands'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
