-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.material_types (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	code varchar(80) NOT NULL,
	name text NOT NULL,
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> ''),
	CHECK (btrim(code) <> '')
);

COMMENT ON TABLE public.material_types IS 'Material type reference data.';
COMMENT ON COLUMN public.material_types.code IS 'Unique material type code';
COMMENT ON COLUMN public.material_types.name IS 'Display name of the material type.';

CREATE UNIQUE INDEX material_types_code_idx
	ON public.material_types USING btree (code);

CREATE UNIQUE INDEX material_types_name_idx
	ON public.material_types USING btree (lower(name));

WITH required(code, description) AS (
	VALUES
		('materialType.create', 'Создание вида материала'),
		('materialType.list', 'Просмотр списка видов материалов'),
		('materialType.detail', 'Просмотр вида материала'),
		('materialType.update', 'Изменение вида материала'),
		('materialType.delete', 'Удаление вида материала')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialType.create'),
		('materialType.list'),
		('materialType.detail'),
		('materialType.update'),
		('materialType.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'materialTypes',
	'/material-types',
	'Виды материалов',
	'Справочники',
	'pi pi-bookmark',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Виды материалов',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Виды материалов'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Виды материалов';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Виды материалов'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Виды материалов',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'materialTypes'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Виды материалов'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Виды материалов',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Виды материалов'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'materialTypes'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

-- default material type
INSERT INTO material_types (id, code, name) VALUES (1, 'temp', 'Распределить') ON CONFLICT DO NOTHING;

COMMIT;
