-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.material_consumption_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	material_consumption_id integer NOT NULL REFERENCES public.material_consumptions(id) ON DELETE CASCADE ON UPDATE CASCADE,
	material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quant numeric(19, 4) NOT NULL,
	CHECK (line_num > 0),
	CHECK (quant > 0)
);

COMMENT ON TABLE public.material_consumption_items IS 'Material consumption document lines.';
COMMENT ON COLUMN public.material_consumption_items.line_num IS 'Line number within the document.';
COMMENT ON COLUMN public.material_consumption_items.material_consumption_id IS 'Parent material consumption document.';
COMMENT ON COLUMN public.material_consumption_items.material_id IS 'Material.';
COMMENT ON COLUMN public.material_consumption_items.measure_unit_id IS 'Measurement unit.';
COMMENT ON COLUMN public.material_consumption_items.quant IS 'Material quantity.';

CREATE UNIQUE INDEX material_consumption_items_material_consumption_id_line_num_idx
	ON public.material_consumption_items USING btree (material_consumption_id, line_num);

WITH required(code, description) AS (
	VALUES
		('materialConsumptionItem.create', 'Создание строки списания материалов'),
		('materialConsumptionItem.list', 'Просмотр строк списания материалов'),
		('materialConsumptionItem.detail', 'Просмотр строки списания материалов'),
		('materialConsumptionItem.update', 'Изменение строки списания материалов'),
		('materialConsumptionItem.delete', 'Удаление строки списания материалов')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialConsumptionItem.create'),
		('materialConsumptionItem.list'),
		('materialConsumptionItem.detail'),
		('materialConsumptionItem.update'),
		('materialConsumptionItem.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

COMMIT;
