-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.main_menus AS menu
USING public.application_routes AS route
WHERE menu.route_id = route.id
	AND menu.role_id = 'admin'
	AND menu.user_id IS NULL
	AND menu.caption = 'Поступления материалов'
	AND route.name = 'materialReceipts';

DELETE FROM public.main_menus AS parent
WHERE parent.role_id = 'admin'
	AND parent.user_id IS NULL
	AND parent.parent_id IS NULL
	AND parent.caption = 'Материалы'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS child
		WHERE child.parent_id = parent.id
	);

DELETE FROM public.application_routes AS route
WHERE route.name = 'materialReceipts'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS menu
		WHERE menu.route_id = route.id
	);

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'materialReceipt.create',
	'materialReceipt.list',
	'materialReceipt.detail',
	'materialReceipt.update',
	'materialReceipt.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'materialReceipt.create',
	'materialReceipt.list',
	'materialReceipt.detail',
	'materialReceipt.update',
	'materialReceipt.delete'
);

DROP TABLE IF EXISTS public.material_receipts;

COMMIT;
