-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'materialTransferItem.create',
	'materialTransferItem.list',
	'materialTransferItem.detail',
	'materialTransferItem.update',
	'materialTransferItem.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'materialTransferItem.create',
	'materialTransferItem.list',
	'materialTransferItem.detail',
	'materialTransferItem.update',
	'materialTransferItem.delete'
);

DROP TABLE IF EXISTS public.material_transfer_items;

COMMIT;
