-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.contacts (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name varchar(250) NOT NULL,
	phone varchar(11),
	email varchar(150),
	employee_post_id integer REFERENCES public.employee_posts(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	is_active boolean NOT NULL DEFAULT true,
	search text NOT NULL,
	CHECK (btrim(name) <> '')
);

COMMENT ON TABLE public.contacts IS 'Contact reference data.';
COMMENT ON COLUMN public.contacts.name IS 'Display name of the contact.';
COMMENT ON COLUMN public.contacts.phone IS 'Contact phone';
COMMENT ON COLUMN public.contacts.email IS 'Contact email';
COMMENT ON COLUMN public.contacts.employee_post_id IS 'contact post';

CREATE UNIQUE INDEX contacts_phone_idx
	ON public.contacts USING btree (phone);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX contacts_search_idx
	ON public.contacts USING GIN (search gin_trgm_ops);

WITH required(code, description) AS (
	VALUES
		('contact.create', 'Создание контакта'),
		('contact.list', 'Просмотр списка контактов'),
		('contact.detail', 'Просмотр контакта'),
		('contact.update', 'Изменение контакта'),
		('contact.delete', 'Удаление контакта')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('contact.create'),
		('contact.list'),
		('contact.detail'),
		('contact.update'),
		('contact.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'contacts',
	'/contacts',
	'Контакты',
	'Справочники',
	'pi pi-id-card',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.section,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Контакты',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Контакты'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Контакты';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Контакты'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Контакты',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'contacts'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Контакты'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Контакты',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Контакты'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'contacts'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);


-- Function: format_phone(text)

CREATE OR REPLACE FUNCTION public.format_phone(text)
RETURNS text AS
$BODY$
	SELECT
		CASE
			WHEN NULLIF(btrim($1), '') IS NULL THEN NULL
			WHEN char_length($1) < 10 THEN $1
			ELSE
				'+' || substr($1, 1, 1) ||
				'(' || substr($1, 2, 3) || ')-' ||
				substr($1, 5, 3) || '-' ||
				substr($1, 8, 2) || '-' ||
				substr($1, 10, 2)
		END;
$BODY$
LANGUAGE sql STABLE;

-- Function: public.contacts_ref(public.contacts)

CREATE OR REPLACE FUNCTION public.contacts_ref(public.contacts)
RETURNS json AS
$BODY$
	SELECT
		CASE
			WHEN $1.id IS NULL THEN NULL
			ELSE json_build_object(
				'keys', json_build_object('id', $1.id),
				'descr', concat_ws(
					', ',
					NULLIF(btrim($1.name), ''),
					public.format_phone($1.phone),
					(
						SELECT NULLIF(btrim(employee_post.name), '')
						FROM public.employee_posts AS employee_post
						WHERE employee_post.id = $1.employee_post_id
					),
					NULLIF(btrim($1.email), '')
				),
				'dataType', 'contacts'
			)
		END;
$BODY$
LANGUAGE sql STABLE;

-- Function: contacts_process()

CREATE OR REPLACE FUNCTION public.contacts_process()
RETURNS trigger AS
$BODY$
BEGIN
	NEW.search := concat_ws(
		' ',
		NULLIF(btrim(NEW.name), ''),
		(
			SELECT NULLIF(btrim(employee_post.name), '')
			FROM public.employee_posts AS employee_post
			WHERE employee_post.id = NEW.employee_post_id
		),
		NULLIF(btrim(NEW.email), ''),
		NULLIF(btrim(NEW.phone), ''),
		public.format_phone(NEW.phone)
	);

	RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

CREATE TRIGGER contacts_trigger_before
BEFORE INSERT OR UPDATE
ON public.contacts
FOR EACH ROW
EXECUTE PROCEDURE public.contacts_process();


COMMIT;
