-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'materialReceiptItem.create',
	'materialReceiptItem.list',
	'materialReceiptItem.detail',
	'materialReceiptItem.update',
	'materialReceiptItem.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'materialReceiptItem.create',
	'materialReceiptItem.list',
	'materialReceiptItem.detail',
	'materialReceiptItem.update',
	'materialReceiptItem.delete'
);

DROP TABLE IF EXISTS public.material_receipt_items;

COMMIT;
