-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.main_menus AS menu
USING public.application_routes AS route
WHERE menu.route_id = route.id
	AND menu.role_id = 'admin'
	AND menu.user_id IS NULL
	AND menu.caption = 'Статусы материалов'
	AND route.name = 'materialStatuses';

DELETE FROM public.main_menus AS parent
WHERE parent.role_id = 'admin'
	AND parent.user_id IS NULL
	AND parent.parent_id IS NULL
	AND parent.caption = 'Статусы материалов'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS child
		WHERE child.parent_id = parent.id
	);

DELETE FROM public.application_routes AS route
WHERE route.name = 'materialStatuses'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS menu
		WHERE menu.route_id = route.id
	);

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'materialStatus.create',
	'materialStatus.list',
	'materialStatus.detail',
	'materialStatus.update',
	'materialStatus.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'materialStatus.create',
	'materialStatus.list',
	'materialStatus.detail',
	'materialStatus.update',
	'materialStatus.delete'
);

DROP VIEW public.material_statuses_list;
DROP TABLE IF EXISTS public.material_statuses;
DROP TYPE IF EXISTS public.material_status_types;

COMMIT;
