BEGIN;

DO $drop_status_code_check$
DECLARE
	constraint_name text;
BEGIN
	SELECT check_constraint.conname
	INTO constraint_name
	FROM pg_catalog.pg_constraint AS check_constraint
	WHERE check_constraint.conrelid = 'public.material_request_statuses'::regclass
		AND check_constraint.contype = 'c'
		AND pg_catalog.pg_get_constraintdef(check_constraint.oid) LIKE '%submitted%'
	LIMIT 1;

	IF constraint_name IS NULL THEN
		RAISE EXCEPTION
			'material_request_statuses workflow-code check was not found';
	END IF;

	EXECUTE format(
		'ALTER TABLE public.material_request_statuses DROP CONSTRAINT %I',
		constraint_name
	);
END;
$drop_status_code_check$;

UPDATE public.material_request_statuses
SET
	code = CASE code
		WHEN 'submitted' THEN 'new'
		WHEN 'in_progress' THEN 'ordered'
		WHEN 'completed' THEN 'fulfilled'
		ELSE code
	END,
	name = CASE code
		WHEN 'submitted' THEN 'Новая'
		WHEN 'in_progress' THEN 'Заказано'
		WHEN 'completed' THEN 'Исполнено'
		ELSE name
	END
WHERE code IN ('submitted', 'in_progress', 'completed');

INSERT INTO public.material_request_statuses (code, name)
VALUES ('supplier_assigned', 'Поставщик назначен')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name;

ALTER TABLE public.material_request_statuses
	ADD CONSTRAINT material_request_statuses_code_values_check CHECK (
		code IN (
			'draft',
			'new',
			'supplier_assigned',
			'ordered',
			'fulfilled',
			'cancelled'
		)
	);

ALTER TABLE public.material_requests
	ADD COLUMN status_id integer;

UPDATE public.material_requests AS request
SET status_id = COALESCE(
	(
		-- Legacy requests could contain lines at different workflow stages.
		-- Roll them up to the earliest stage explicitly by stable code; status
		-- identity values are not part of the workflow contract.
		SELECT item.status_id
		FROM public.material_request_items AS item
		JOIN public.material_request_statuses AS item_status
			ON item_status.id = item.status_id
		WHERE item.material_request_id = request.id
		ORDER BY
			CASE item_status.code
				WHEN 'draft' THEN 1
				WHEN 'new' THEN 2
				WHEN 'supplier_assigned' THEN 3
				WHEN 'ordered' THEN 4
				WHEN 'fulfilled' THEN 5
				WHEN 'cancelled' THEN 6
				ELSE 7
			END,
			item.id
		LIMIT 1
	),
	(
		SELECT status.id
		FROM public.material_request_statuses AS status
		WHERE status.code = 'draft'
	)
);

ALTER TABLE public.material_requests
	ALTER COLUMN status_id SET DEFAULT 1,
	ALTER COLUMN status_id SET NOT NULL,
	ADD CONSTRAINT material_requests_status_id_fkey
		FOREIGN KEY (status_id)
		REFERENCES public.material_request_statuses(id)
		ON DELETE RESTRICT
		ON UPDATE CASCADE;

COMMENT ON COLUMN public.material_requests.status_id IS
	'Request workflow status maintained from the statuses of its lines.';

CREATE INDEX material_requests_status_id_idx
	ON public.material_requests USING btree (status_id);

CREATE OR REPLACE VIEW public.material_requests_list AS
SELECT
	request.id,
	request.date,
	request.construction_site_id,
	request.construction_manager_id,
	request.comment,
	request.version,
	public.construction_sites_ref(site) AS construction_site,
	public.users_ref(manager) AS construction_manager,
	request.status_id,
	public.material_request_statuses_ref(status) AS status
FROM public.material_requests AS request
LEFT JOIN public.construction_sites AS site
	ON site.id = request.construction_site_id
LEFT JOIN public.users AS manager
	ON manager.id = request.construction_manager_id
LEFT JOIN public.material_request_statuses AS status
	ON status.id = request.status_id;

CREATE TABLE public.material_request_supplier_assignments (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	date timestamp with time zone NOT NULL DEFAULT now(),
	supply_manager_id integer NOT NULL
		REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	comment text,
	version bigint NOT NULL DEFAULT 1,
	CHECK (version > 0)
);

COMMENT ON TABLE public.material_request_supplier_assignments IS
	'Supply-manager documents assigning one supplier to each material request line.';
COMMENT ON COLUMN public.material_request_supplier_assignments.date IS
	'Document date and time.';
COMMENT ON COLUMN public.material_request_supplier_assignments.supply_manager_id IS
	'Supply manager who assigned the suppliers.';
COMMENT ON COLUMN public.material_request_supplier_assignments.comment IS
	'Optional assignment comment.';
COMMENT ON COLUMN public.material_request_supplier_assignments.version IS
	'Optimistic concurrency version.';

CREATE INDEX material_request_supplier_assignments_manager_date_idx
	ON public.material_request_supplier_assignments USING btree (
		supply_manager_id,
		date
	);

CREATE TABLE public.material_request_supplier_assignment_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	material_request_supplier_assignment_id integer NOT NULL
		REFERENCES public.material_request_supplier_assignments(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	material_request_item_id integer NOT NULL
		REFERENCES public.material_request_items(id)
		ON DELETE RESTRICT ON UPDATE CASCADE,
	supplier_id integer NOT NULL
		REFERENCES public.suppliers(id)
		ON DELETE RESTRICT ON UPDATE CASCADE,
	CHECK (line_num > 0)
);

COMMENT ON TABLE public.material_request_supplier_assignment_items IS
	'Lines of a supply-manager supplier-assignment document.';
COMMENT ON COLUMN public.material_request_supplier_assignment_items.line_num IS
	'Line number within the assignment document.';
COMMENT ON COLUMN public.material_request_supplier_assignment_items.material_request_supplier_assignment_id IS
	'Parent supplier-assignment document.';
COMMENT ON COLUMN public.material_request_supplier_assignment_items.material_request_item_id IS
	'Original material request line being assigned.';
COMMENT ON COLUMN public.material_request_supplier_assignment_items.supplier_id IS
	'Supplier assigned to the complete original request line.';

CREATE UNIQUE INDEX material_request_supplier_assignment_items_assignment_line_idx
	ON public.material_request_supplier_assignment_items USING btree (
		material_request_supplier_assignment_id,
		line_num
	);

CREATE UNIQUE INDEX material_request_supplier_assignment_items_request_item_idx
	ON public.material_request_supplier_assignment_items USING btree (
		material_request_item_id
	);

CREATE INDEX material_request_supplier_assignment_items_supplier_id_idx
	ON public.material_request_supplier_assignment_items USING btree (supplier_id);

CREATE OR REPLACE VIEW public.material_request_supplier_assignments_list AS
SELECT
	assignment.id,
	assignment.date,
	assignment.supply_manager_id,
	assignment.comment,
	assignment.version,
	public.users_ref(supply_manager) AS supply_manager
FROM public.material_request_supplier_assignments AS assignment
LEFT JOIN public.users AS supply_manager
	ON supply_manager.id = assignment.supply_manager_id;

CREATE OR REPLACE VIEW public.material_request_supplier_assignment_items_list AS
SELECT
	item.id,
	item.line_num,
	item.material_request_supplier_assignment_id,
	item.material_request_item_id,
	item.supplier_id,
	public.suppliers_ref(supplier) AS supplier
FROM public.material_request_supplier_assignment_items AS item
LEFT JOIN public.suppliers AS supplier
	ON supplier.id = item.supplier_id;

WITH required(code, description) AS (
	VALUES
		(
			'materialRequestSupplierAssignment.create',
			'Назначение поставщиков по заявкам на материалы'
		),
		(
			'materialRequestSupplierAssignment.list',
			'Просмотр истории назначений поставщиков'
		),
		(
			'materialRequestSupplierAssignment.detail',
			'Просмотр назначения поставщиков'
		),
		(
			'materialRequestSupplierAssignmentItem.list',
			'Просмотр строк назначений поставщиков'
		),
		(
			'materialRequestSupplierAssignmentItem.detail',
			'Просмотр строки назначения поставщика'
		)
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types),
		('supply_manager'::public.role_types)
), required(permission_code) AS (
	VALUES
		('materialRequestSupplierAssignment.create'),
		('materialRequestSupplierAssignment.list'),
		('materialRequestSupplierAssignment.detail')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

WITH required(permission_code) AS (
	VALUES
		('materialRequestSupplierAssignmentItem.list'),
		('materialRequestSupplierAssignmentItem.detail')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'admin'::public.role_types, required.permission_code
FROM required
ON CONFLICT DO NOTHING;

DELETE FROM public.role_permissions
WHERE role_id = 'supply_manager'::public.role_types
	AND permission_code IN (
		'materialRequest.list',
		'materialRequest.detail',
		'materialRequest.update'
	);

WITH aliases(table_name, column_name, column_alias) AS (
	VALUES
		('material_requests', 'status_id', 'Статус'),
		('material_request_supplier_assignments', 'id', 'Идентификатор'),
		('material_request_supplier_assignments', 'date', 'Дата и время'),
		('material_request_supplier_assignments', 'supply_manager_id', 'Менеджер снабжения'),
		('material_request_supplier_assignments', 'comment', 'Комментарий'),
		('material_request_supplier_assignments', 'version', 'Версия'),
		('material_request_supplier_assignment_items', 'id', 'Идентификатор'),
		('material_request_supplier_assignment_items', 'line_num', 'Номер строки'),
		(
			'material_request_supplier_assignment_items',
			'material_request_supplier_assignment_id',
			'Назначение поставщиков'
		),
		(
			'material_request_supplier_assignment_items',
			'material_request_item_id',
			'Строка заявки на материалы'
		),
		('material_request_supplier_assignment_items', 'supplier_id', 'Поставщик')
)
INSERT INTO public.audit_column_aliases (
	table_name,
	column_name,
	column_alias,
	is_active
)
SELECT aliases.table_name, aliases.column_name, aliases.column_alias, true
FROM aliases
ON CONFLICT (table_name, column_name) DO UPDATE
SET
	column_alias = EXCLUDED.column_alias,
	is_active = true;

CREATE TRIGGER audit_log_material_request_supplier_assignments
AFTER INSERT OR UPDATE OR DELETE
ON public.material_request_supplier_assignments
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

CREATE TRIGGER audit_log_material_request_supplier_assignment_items
AFTER INSERT OR UPDATE OR DELETE
ON public.material_request_supplier_assignment_items
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

COMMIT;
