BEGIN;

CREATE TABLE public.entity_contacts (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	entity_type varchar(250) NOT NULL,
	entity_id int NOT NULL,
	contact_id integer NOT NULL REFERENCES public.contacts(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	is_active boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX entity_contacts_contact_idx
	ON public.entity_contacts USING btree (entity_type, entity_id, contact_id);

CREATE OR REPLACE VIEW public.entity_contacts_list AS
	SELECT
		e_ct.id,
		e_ct.entity_type,
		e_ct.entity_id,
		CASE
			WHEN e_ct.entity_type = 'users' THEN users_ref(u)
			WHEN e_ct.entity_type = 'suppliers' THEN suppliers_ref(spl)
			ELSE NULL
		END AS entity,
		e_ct.contact_id,
		contacts_ref(ct) AS contact,
		json_build_object(
			'name', ct.name,
			'phone', ct.phone,
			'email', ct.email,
			'employee_post', p.name
		) AS contact_attrs,
		e_ct.is_active
	FROM public.entity_contacts AS e_ct
	LEFT JOIN public.users AS u
		ON e_ct.entity_type = 'users' AND u.id = e_ct.entity_id
	LEFT JOIN public.suppliers AS spl
		ON e_ct.entity_type = 'suppliers' AND spl.id = e_ct.entity_id
	LEFT JOIN public.contacts AS ct
		ON ct.id = e_ct.contact_id
	LEFT JOIN public.employee_posts AS p
		ON p.id = ct.employee_post_id
	ORDER BY
		e_ct.entity_type,
		CASE
			WHEN e_ct.entity_type = 'users' THEN users_ref(u)->>'descr'
			WHEN e_ct.entity_type = 'suppliers' THEN suppliers_ref(spl)->>'descr'
			ELSE NULL
		END,
		ct.name,
		e_ct.id;

WITH required(code, description) AS (
	VALUES
		('entityContact.create', 'Создание связи контакта с объектом'),
		('entityContact.list', 'Просмотр контактов объекта'),
		('entityContact.detail', 'Просмотр связи контакта с объектом'),
		('entityContact.update', 'Изменение связи контакта с объектом'),
		('entityContact.delete', 'Удаление связи контакта с объектом')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('entityContact.create'),
		('entityContact.list'),
		('entityContact.detail'),
		('entityContact.update'),
		('entityContact.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

COMMIT;
