-- Code generated by cmd/codegen. Review before applying.

BEGIN;

DELETE FROM public.main_menus AS menu
USING public.application_routes AS route
WHERE menu.route_id = route.id
	AND menu.role_id = 'admin'
	AND menu.user_id IS NULL
	AND menu.caption = 'Единицы измерения'
	AND route.name = 'measureUnits';

DELETE FROM public.main_menus AS parent
WHERE parent.role_id = 'admin'
	AND parent.user_id IS NULL
	AND parent.parent_id IS NULL
	AND parent.caption = 'Единицы'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS child
		WHERE child.parent_id = parent.id
	);

DELETE FROM public.application_routes AS route
WHERE route.name = 'measureUnits'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS menu
		WHERE menu.route_id = route.id
	);

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'measureUnit.create',
	'measureUnit.list',
	'measureUnit.detail',
	'measureUnit.update',
	'measureUnit.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'measureUnit.create',
	'measureUnit.list',
	'measureUnit.detail',
	'measureUnit.update',
	'measureUnit.delete'
);

DROP TABLE IF EXISTS public.measure_units;

COMMIT;
