// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type ConstructionSiteService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewConstructionSiteService(ctx webapp.ServiceContext) any {
	return &ConstructionSiteService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterConstructionSiteService() {
	webapp.MustRegisterService(
		"ConstructionSite",
		&ConstructionSiteService{},
		NewConstructionSiteService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *ConstructionSiteService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.ConstructionSite],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert construction site: %w", err)
	}

	return result, nil
}

func (s *ConstructionSiteService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.ConstructionSiteKey, *models.ConstructionSite],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("construction site key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("construction site id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update construction site: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"construction site not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *ConstructionSiteService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("construction site id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.ConstructionSiteKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete construction site: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"construction site not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *ConstructionSiteService) Detail(
	ctx context.Context,
	id int,
) (*models.ConstructionSite, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("construction site id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.ConstructionSiteKey{
			ID: id,
		},
		&models.ConstructionSite{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"construction site not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch construction site: %w", err)
	}

	return result, nil
}

func (s *ConstructionSiteService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.ConstructionSite], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.ConstructionSite]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.ConstructionSite]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.ConstructionSite{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.ConstructionSite]{}, fmt.Errorf(
			"fetch construction site collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.ConstructionSite]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *ConstructionSiteService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *ConstructionSiteService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
