// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type ContactService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewContactService(ctx webapp.ServiceContext) any {
	return &ContactService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterContactService() {
	webapp.MustRegisterService(
		"Contact",
		&ContactService{},
		NewContactService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *ContactService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.Contact],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert contact: %w", err)
	}

	return result, nil
}

func (s *ContactService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.ContactKey, *models.Contact],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("contact key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("contact id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update contact: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"contact not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *ContactService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("contact id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.ContactKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete contact: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"contact not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *ContactService) Detail(
	ctx context.Context,
	id int,
) (*models.Contact, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("contact id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.ContactKey{
			ID: id,
		},
		&models.Contact{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"contact not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch contact: %w", err)
	}

	return result, nil
}

func (s *ContactService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.Contact], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.Contact]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.Contact]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.Contact{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.Contact]{}, fmt.Errorf(
			"fetch contact collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.Contact]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *ContactService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *ContactService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
