// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type EmployeePostService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewEmployeePostService(ctx webapp.ServiceContext) any {
	return &EmployeePostService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterEmployeePostService() {
	webapp.MustRegisterService(
		"EmployeePost",
		&EmployeePostService{},
		NewEmployeePostService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *EmployeePostService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.EmployeePost],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert employee post: %w", err)
	}

	return result, nil
}

func (s *EmployeePostService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.EmployeePostKey, *models.EmployeePost],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("employee post key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("employee post id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update employee post: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"employee post not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *EmployeePostService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("employee post id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.EmployeePostKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete employee post: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"employee post not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *EmployeePostService) Detail(
	ctx context.Context,
	id int,
) (*models.EmployeePost, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("employee post id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.EmployeePostKey{
			ID: id,
		},
		&models.EmployeePost{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"employee post not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch employee post: %w", err)
	}

	return result, nil
}

func (s *EmployeePostService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.EmployeePost], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.EmployeePost]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.EmployeePost]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.EmployeePost{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.EmployeePost]{}, fmt.Errorf(
			"fetch employee post collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.EmployeePost]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *EmployeePostService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *EmployeePostService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
