// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type EntityContactService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewEntityContactService(ctx webapp.ServiceContext) any {
	return &EntityContactService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterEntityContactService() {
	webapp.MustRegisterService(
		"EntityContact",
		&EntityContactService{},
		NewEntityContactService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *EntityContactService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.EntityContact],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert entity contact: %w", err)
	}

	return result, nil
}

func (s *EntityContactService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.EntityContactKey, *models.EntityContact],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("entity contact key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("entity contact id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update entity contact: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"entity contact not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *EntityContactService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("entity contact id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.EntityContactKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete entity contact: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"entity contact not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *EntityContactService) Detail(
	ctx context.Context,
	id int,
) (*models.EntityContact, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("entity contact id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.EntityContactKey{
			ID: id,
		},
		&models.EntityContact{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"entity contact not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch entity contact: %w", err)
	}

	return result, nil
}

func (s *EntityContactService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.EntityContactList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.EntityContactList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.EntityContactList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.EntityContactList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.EntityContactList]{}, fmt.Errorf(
			"fetch entity contact collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.EntityContactList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *EntityContactService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *EntityContactService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
