// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialRequestItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialRequestItemService(ctx webapp.ServiceContext) any {
	return &MaterialRequestItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialRequestItemService() {
	webapp.MustRegisterService(
		"MaterialRequestItem",
		&MaterialRequestItemService{},
		NewMaterialRequestItemService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialRequestItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialRequestItemList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestItemList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestItemList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialRequestItemList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestItemList]{}, fmt.Errorf(
			"fetch material request item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialRequestItemList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialRequestItemService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialRequestItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
