// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialRequestSupplierAssignmentItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialRequestSupplierAssignmentItemService(ctx webapp.ServiceContext) any {
	return &MaterialRequestSupplierAssignmentItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialRequestSupplierAssignmentItemService() {
	webapp.MustRegisterService(
		"MaterialRequestSupplierAssignmentItem",
		&MaterialRequestSupplierAssignmentItemService{},
		NewMaterialRequestSupplierAssignmentItemService,
	)
}

func (s *MaterialRequestSupplierAssignmentItemService) Detail(
	ctx context.Context,
	id int,
) (*models.MaterialRequestSupplierAssignmentItem, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("material request supplier assignment item id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.MaterialRequestSupplierAssignmentItemKey{
			ID: id,
		},
		&models.MaterialRequestSupplierAssignmentItem{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"material request supplier assignment item not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch material request supplier assignment item: %w", err)
	}

	return result, nil
}

func (s *MaterialRequestSupplierAssignmentItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialRequestSupplierAssignmentItemList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestSupplierAssignmentItemList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestSupplierAssignmentItemList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialRequestSupplierAssignmentItemList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestSupplierAssignmentItemList]{}, fmt.Errorf(
			"fetch material request supplier assignment item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialRequestSupplierAssignmentItemList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialRequestSupplierAssignmentItemService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialRequestSupplierAssignmentItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
