// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialReceiptService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialReceiptService(ctx webapp.ServiceContext) any {
	return &MaterialReceiptService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialReceiptService() {
	webapp.MustRegisterService(
		"MaterialReceipt",
		&MaterialReceiptService{},
		NewMaterialReceiptService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialReceiptService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialReceiptList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialReceiptList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptList]{}, fmt.Errorf(
			"fetch material receipt collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialReceiptList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialReceiptService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialReceiptService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
