// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"github.com/dronm/ds/v4"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/webapp"
)

type MaterialRequestSupplierAssignmentService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialRequestSupplierAssignmentService(ctx webapp.ServiceContext) any {
	return &MaterialRequestSupplierAssignmentService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialRequestSupplierAssignmentService() {
	webapp.MustRegisterService(
		"MaterialRequestSupplierAssignment",
		&MaterialRequestSupplierAssignmentService{},
		NewMaterialRequestSupplierAssignmentService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialRequestSupplierAssignmentService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialRequestSupplierAssignmentService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
