// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialReceiptItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialReceiptItemService(ctx webapp.ServiceContext) any {
	return &MaterialReceiptItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialReceiptItemService() {
	webapp.MustRegisterService(
		"MaterialReceiptItem",
		&MaterialReceiptItemService{},
		NewMaterialReceiptItemService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialReceiptItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialReceiptItemList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptItemList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptItemList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialReceiptItemList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialReceiptItemList]{}, fmt.Errorf(
			"fetch material receipt item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialReceiptItemList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialReceiptItemService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialReceiptItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
