// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialConsumptionService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialConsumptionService(ctx webapp.ServiceContext) any {
	return &MaterialConsumptionService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialConsumptionService() {
	webapp.MustRegisterService(
		"MaterialConsumption",
		&MaterialConsumptionService{},
		NewMaterialConsumptionService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialConsumptionService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialConsumptionList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialConsumptionList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionList]{}, fmt.Errorf(
			"fetch material consumption collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialConsumptionList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialConsumptionService) requireSession() error {
	return requireMaterialConsumptionAdminSession(s.Session, "materialConsumption")
}

func (s *MaterialConsumptionService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
