// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialRequestService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialRequestService(ctx webapp.ServiceContext) any {
	return &MaterialRequestService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialRequestService() {
	webapp.MustRegisterService(
		"MaterialRequest",
		&MaterialRequestService{},
		NewMaterialRequestService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialRequestService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialRequestList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialRequestList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestList]{}, fmt.Errorf(
			"fetch material request collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialRequestList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialRequestService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialRequestService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
