// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialService(ctx webapp.ServiceContext) any {
	return &MaterialService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialService() {
	webapp.MustRegisterService(
		"Material",
		&MaterialService{},
		NewMaterialService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.Material],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert material: %w", err)
	}

	return result, nil
}

func (s *MaterialService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.MaterialKey, *models.Material],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("material key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("material id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update material: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"material not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *MaterialService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("material id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.MaterialKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete material: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"material not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *MaterialService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialList]{}, fmt.Errorf(
			"fetch material collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
