// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialConsumptionItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialConsumptionItemService(ctx webapp.ServiceContext) any {
	return &MaterialConsumptionItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialConsumptionItemService() {
	webapp.MustRegisterService(
		"MaterialConsumptionItem",
		&MaterialConsumptionItemService{},
		NewMaterialConsumptionItemService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialConsumptionItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialConsumptionItemList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionItemList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionItemList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialConsumptionItemList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialConsumptionItemList]{}, fmt.Errorf(
			"fetch material consumption item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialConsumptionItemList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialConsumptionItemService) requireSession() error {
	return requireMaterialConsumptionAdminSession(s.Session, "materialConsumptionItem")
}

func (s *MaterialConsumptionItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
