// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialTransferService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialTransferService(ctx webapp.ServiceContext) any {
	return &MaterialTransferService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialTransferService() {
	webapp.MustRegisterService(
		"MaterialTransfer",
		&MaterialTransferService{},
		NewMaterialTransferService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialTransferService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialTransferList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialTransferList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferList]{}, fmt.Errorf(
			"fetch material transfer collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialTransferList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialTransferService) requireSession() error {
	return requireMaterialTransferAdminSession(s.Session, "materialTransfer")
}

func (s *MaterialTransferService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
