// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialRequestStatusService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialRequestStatusService(ctx webapp.ServiceContext) any {
	return &MaterialRequestStatusService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialRequestStatusService() {
	webapp.MustRegisterService(
		"MaterialRequestStatus",
		&MaterialRequestStatusService{},
		NewMaterialRequestStatusService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialRequestStatusService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.MaterialRequestStatusKey, *models.MaterialRequestStatus],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("material request status key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("material request status id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update material request status: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"material request status not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *MaterialRequestStatusService) Detail(
	ctx context.Context,
	id int,
) (*models.MaterialRequestStatus, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("material request status id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.MaterialRequestStatusKey{
			ID: id,
		},
		&models.MaterialRequestStatus{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"material request status not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch material request status: %w", err)
	}

	return result, nil
}

func (s *MaterialRequestStatusService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialRequestStatus], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestStatus]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestStatus]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialRequestStatus{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialRequestStatus]{}, fmt.Errorf(
			"fetch material request status collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialRequestStatus]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialRequestStatusService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialRequestStatusService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
