// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaterialTransferItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaterialTransferItemService(ctx webapp.ServiceContext) any {
	return &MaterialTransferItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaterialTransferItemService() {
	webapp.MustRegisterService(
		"MaterialTransferItem",
		&MaterialTransferItemService{},
		NewMaterialTransferItemService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MaterialTransferItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaterialTransferItemList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferItemList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferItemList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaterialTransferItemList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaterialTransferItemList]{}, fmt.Errorf(
			"fetch material transfer item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaterialTransferItemList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaterialTransferItemService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaterialTransferItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
