// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MeasureUnitService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMeasureUnitService(ctx webapp.ServiceContext) any {
	return &MeasureUnitService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMeasureUnitService() {
	webapp.MustRegisterService(
		"MeasureUnit",
		&MeasureUnitService{},
		NewMeasureUnitService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *MeasureUnitService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.MeasureUnit],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert measure unit: %w", err)
	}

	return result, nil
}

func (s *MeasureUnitService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.MeasureUnitKey, *models.MeasureUnit],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("measure unit key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("measure unit id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update measure unit: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"measure unit not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *MeasureUnitService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("measure unit id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.MeasureUnitKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete measure unit: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"measure unit not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *MeasureUnitService) Detail(
	ctx context.Context,
	id int,
) (*models.MeasureUnit, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("measure unit id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.MeasureUnitKey{
			ID: id,
		},
		&models.MeasureUnit{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"measure unit not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch measure unit: %w", err)
	}

	return result, nil
}

func (s *MeasureUnitService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MeasureUnit], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MeasureUnit]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MeasureUnit]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MeasureUnit{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MeasureUnit]{}, fmt.Errorf(
			"fetch measure unit collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MeasureUnit]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MeasureUnitService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MeasureUnitService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
