// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type OrderImportanceService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewOrderImportanceService(ctx webapp.ServiceContext) any {
	return &OrderImportanceService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterOrderImportanceService() {
	webapp.MustRegisterService(
		"OrderImportance",
		&OrderImportanceService{},
		NewOrderImportanceService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *OrderImportanceService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.OrderImportance],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert order importance: %w", err)
	}

	return result, nil
}

func (s *OrderImportanceService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.OrderImportanceKey, *models.OrderImportance],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order importance key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order importance id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update order importance: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"order importance not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *OrderImportanceService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order importance id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.OrderImportanceKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete order importance: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"order importance not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *OrderImportanceService) Detail(
	ctx context.Context,
	id int,
) (*models.OrderImportance, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("order importance id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.OrderImportanceKey{
			ID: id,
		},
		&models.OrderImportance{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"order importance not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch order importance: %w", err)
	}

	return result, nil
}

func (s *OrderImportanceService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.OrderImportance], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.OrderImportance]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.OrderImportance]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.OrderImportance{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.OrderImportance]{}, fmt.Errorf(
			"fetch order importance collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.OrderImportance]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *OrderImportanceService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *OrderImportanceService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
