// Code generated by cmd/codegen. DO NOT EDIT.

package services

func RegisterGeneratedServices() {
	RegisterConstructionSiteService()
	RegisterContactService()
	RegisterEmployeePostService()
	RegisterEntityContactService()
	RegisterMaterialService()
	RegisterMaterialConsumptionService()
	RegisterMaterialConsumptionItemService()
	RegisterMaterialReceiptService()
	RegisterMaterialReceiptItemService()
	RegisterMaterialStatusService()
	RegisterMaterialTransferService()
	RegisterMaterialTransferItemService()
	RegisterMaterialTypeService()
	RegisterMaxUserService()
	RegisterMeasureUnitService()
	RegisterNotificationTemplateService()
	RegisterSupplierService()
}
