// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/skstruktura/internal/apperrors"
	"github.com/dronm/skstruktura/internal/models"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type SupplierService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewSupplierService(ctx webapp.ServiceContext) any {
	return &SupplierService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterSupplierService() {
	webapp.MustRegisterService(
		"Supplier",
		&SupplierService{},
		NewSupplierService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *SupplierService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.Supplier],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert supplier: %w", err)
	}

	return result, nil
}

func (s *SupplierService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.SupplierKey, *models.Supplier],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("supplier key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("supplier id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update supplier: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"supplier not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *SupplierService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("supplier id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.SupplierKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete supplier: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"supplier not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *SupplierService) Detail(
	ctx context.Context,
	id int,
) (*models.Supplier, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("supplier id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.SupplierKey{
			ID: id,
		},
		&models.Supplier{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"supplier not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch supplier: %w", err)
	}

	return result, nil
}

func (s *SupplierService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.Supplier], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.Supplier]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.Supplier]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.Supplier{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.Supplier]{}, fmt.Errorf(
			"fetch supplier collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.Supplier]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *SupplierService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *SupplierService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
